[package]
name                  = "gui"
publish               = false
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
authors.workspace     = true
license.workspace     = true
homepage.workspace    = true
repository.workspace  = true
description           = "Aphrody — UI surface (Rust Native)."

[lints]
workspace = true

[dependencies]
wry        = { workspace = true }
tao        = { workspace = true }
tokio      = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
mimalloc           = { workspace = true }
backend    = { path = "../backend" }
base       = { path = "../base" }
