[book]
authors = ["Aphrody Authors"]
language = "fr"
multilingual = false
src = "docs"
title = "Google OS & Aphrody Documentation"

[output.html]
git-repository-url = "https://github.com/aphrody-code/aphrody"
