# Nightly Rust pinned for production builds.
# Google-grade: rustc nightly + full instrumentation toolchain.
[toolchain]
channel    = "nightly"
profile    = "minimal"
components = [
    "rust-src",
    "rustfmt",
    "clippy",
    "miri",
    "llvm-tools-preview",
    "rust-analyzer",
    "rustc-codegen-cranelift-preview",
]
targets = [
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "wasm32-unknown-unknown",
    "wasm32-wasip1",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-linux-android",
    "i686-linux-android",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
]
