# SPDX-License-Identifier: Apache-2.0
[package]
name                   = "aphrody-terminal-vt"
publish                = false
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
homepage.workspace     = true
repository.workspace   = true
license.workspace      = true
description            = "Pure Rust VT/ANSI parser and screen buffer (no_std-compatible)."

[lints]
workspace = true

[dependencies]
vte      = { workspace = true }
bitflags = { workspace = true }
base64   = { workspace = true }
