import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";

const tokensDir = join(__dirname, "../tokens");
const colorsJson = JSON.parse(readFileSync(join(tokensDir, "colors.json"), "utf-8"));
const spacingJson = JSON.parse(readFileSync(join(tokensDir, "spacing.json"), "utf-8"));
const typoJson = JSON.parse(readFileSync(join(tokensDir, "typography.json"), "utf-8"));

// --- Helper Functions ---
function ensureDir(path: string) {
  if (!existsSync(dirname(path))) {
    mkdirSync(dirname(path), { recursive: true });
  }
}

function hexToUint32(hex: string): string {
  // "#FF0000" -> "0xFF0000"
  return hex.replace("#", "0x").toUpperCase();
}

// Extract base objects
const brandColors = colorsJson.colors.brand;
const textColors = colorsJson.colors.text;
const statusColors = colorsJson.colors.status;

// ============================================================================
// 1. Web/Node: TypeScript (packages/ui/index.ts)
// ============================================================================
const tsPath = join(__dirname, "../index.ts");
let tsStr = `// Auto-generated by @aphrody-code/ui Pentalingual Compiler\n\n`;
tsStr += `export const Theme = {\n`;
tsStr += `  colors: ${JSON.stringify(colorsJson.colors, null, 4)},\n`;
tsStr += `  spacing: ${JSON.stringify(spacingJson.spacing, null, 4)},\n`;
tsStr += `  typography: ${JSON.stringify(typoJson.typography, null, 4)}\n`;
tsStr += `};\n`;
ensureDir(tsPath);
writeFileSync(tsPath, tsStr);
console.log("✅ Generated TypeScript Module");

// ============================================================================
// 2. C# CLI: Spectre.Console (src/Winclean.Cli.Legacy/UI/StyleGuide.cs)
// ============================================================================
const csPath = join(__dirname, "../../../src/Winclean.Cli.Legacy/UI/StyleGuide.cs");
let csStr = `// Auto-generated by @aphrody-code/ui
using Spectre.Console;

namespace WinClean.CLI.UI;

internal static class StyleGuide
{
    public static readonly Color Primary = Color.FromHex("${brandColors.primary.value}");
    public static readonly Color Secondary = Color.FromHex("${brandColors.secondary.value}");
    public static readonly Color TextPrimary = Color.FromHex("${textColors.primary.value}");
    public static readonly Color TextSecondary = Color.FromHex("${textColors.secondary.value}");
    public static readonly Color Success = Color.FromHex("${statusColors.success.value}");
    public static readonly Color Warning = Color.FromHex("${statusColors.warning.value}");
    public static readonly Color Danger = Color.FromHex("${statusColors.danger.value}");

    public static readonly Style TitleStyle = new Style(Primary, decoration: Decoration.Bold);
    public static readonly Style ErrorStyle = new Style(Danger, decoration: Decoration.Bold);
    public static readonly Style SuccessStyle = new Style(Success, decoration: Decoration.Bold);
    public static readonly Style DimmedStyle = new Style(TextSecondary);
}
`;
ensureDir(csPath);
writeFileSync(csPath, csStr);
console.log("✅ Generated C# CLI StyleGuide");

// ============================================================================
// 3. C++20: Header (src/Winclean.NativeCore/theme.hpp)
// ============================================================================
const cppPath = join(__dirname, "../../../src/Winclean.NativeCore/theme.hpp");
let cppStr = `// Auto-generated by @aphrody-code/ui
#pragma once
#include <cstdint>

namespace winclean::theme::colors {
    constexpr uint32_t Primary = ${hexToUint32(brandColors.primary.value)};
    constexpr uint32_t Secondary = ${hexToUint32(brandColors.secondary.value)};
    constexpr uint32_t TextPrimary = ${hexToUint32(textColors.primary.value)};
    constexpr uint32_t TextSecondary = ${hexToUint32(textColors.secondary.value)};
    constexpr uint32_t Success = ${hexToUint32(statusColors.success.value)};
    constexpr uint32_t Warning = ${hexToUint32(statusColors.warning.value)};
    constexpr uint32_t Danger = ${hexToUint32(statusColors.danger.value)};
}
`;
ensureDir(cppPath);
writeFileSync(cppPath, cppStr);
console.log("✅ Generated C++ Header");

// ============================================================================
// 4. Python: Dataclass (scripts/python/theme.py)
// ============================================================================
const pyPath = join(__dirname, "../../../scripts/python/theme.py");
let pyStr = `# Auto-generated by @aphrody-code/ui
from dataclasses import dataclass

@dataclass(frozen=True)
class ThemeColors:
    PRIMARY: str = "${brandColors.primary.value}"
    SECONDARY: str = "${brandColors.secondary.value}"
    TEXT_PRIMARY: str = "${textColors.primary.value}"
    TEXT_SECONDARY: str = "${textColors.secondary.value}"
    SUCCESS: str = "${statusColors.success.value}"
    WARNING: str = "${statusColors.warning.value}"
    DANGER: str = "${statusColors.danger.value}"

COLORS = ThemeColors()
`;
ensureDir(pyPath);
writeFileSync(pyPath, pyStr);
console.log("✅ Generated Python Dataclass");

console.log("🚀 Pentalingual UI Compilation Complete!");
