// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThemeConfig = { seed_color: string, dark_mode: boolean, contrast_level: number, };
