// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdAlert as MdAlertElement } from "@aphrody/material-web/alert/alert.js";

export const MdAlert = createComponent({
  react: React,
  tagName: "md-alert",
  elementClass: MdAlertElement,
  events: { onClose: "close" },
});
