// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdBottomAppBar as MdBottomAppBarElement} from '@aphrody/material-web/appbar/bottom-app-bar.js';
import {MdTopAppBar as MdTopAppBarElement} from '@aphrody/material-web/appbar/top-app-bar.js';

export const MdBottomAppBar = createComponent({
  react: React,
  tagName: 'md-bottom-app-bar',
  elementClass: MdBottomAppBarElement,
  events: {},
});

export const MdTopAppBar = createComponent({
  react: React,
  tagName: 'md-top-app-bar',
  elementClass: MdTopAppBarElement,
  events: {},
});
