// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdAutocomplete as MdAutocompleteElement} from '@aphrody/material-web/autocomplete/autocomplete.js';

export const MdAutocomplete = createComponent({
  react: React,
  tagName: 'md-autocomplete',
  elementClass: MdAutocompleteElement,
  events: {onInput: 'input', onSelect: 'autocomplete:select'},
});
