// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdAvatar as MdAvatarElement } from "@aphrody-code/material-web/avatar/avatar.js";
import { MdAvatarGroup as MdAvatarGroupElement } from "@aphrody-code/material-web/avatar/avatar-group.js";

export const MdAvatar = createComponent({
  react: React,
  tagName: "md-avatar",
  elementClass: MdAvatarElement,
  events: { onError: "error" },
});

export const MdAvatarGroup = createComponent({
  react: React,
  tagName: "md-avatar-group",
  elementClass: MdAvatarGroupElement,
  events: {},
});
