// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdBackdrop as MdBackdropElement } from "@aphrody/material-web/backdrop/backdrop.js";

export const MdBackdrop = createComponent({
  react: React,
  tagName: "md-backdrop",
  elementClass: MdBackdropElement,
  events: {},
});
