// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdBadge as MdBadgeElement} from '@aphrody/material-web/badge/badge.js';

export const MdBadge = createComponent({
  react: React,
  tagName: 'md-badge',
  elementClass: MdBadgeElement,
  events: {},
});
