// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdBreadcrumbs as MdBreadcrumbsElement } from "@aphrody/material-web/breadcrumbs/breadcrumbs.js";

export const MdBreadcrumbs = createComponent({
  react: React,
  tagName: "md-breadcrumbs",
  elementClass: MdBreadcrumbsElement,
  events: {},
});
