// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdButtonGroup as MdButtonGroupElement} from '@aphrody/material-web/buttongroup/button-group.js';

export const MdButtonGroup = createComponent({
  react: React,
  tagName: 'md-button-group',
  elementClass: MdButtonGroupElement,
  events: {onChange: 'button-group:change'},
});
