// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdElevatedButton as MdElevatedButtonElement } from "@aphrody/material-web/button/elevated-button.js";
import { MdFilledButton as MdFilledButtonElement } from "@aphrody/material-web/button/filled-button.js";
import { MdFilledTonalButton as MdFilledTonalButtonElement } from "@aphrody/material-web/button/filled-tonal-button.js";
import { MdOutlinedButton as MdOutlinedButtonElement } from "@aphrody/material-web/button/outlined-button.js";
import { MdTextButton as MdTextButtonElement } from "@aphrody/material-web/button/text-button.js";

export const MdElevatedButton = createComponent({
  react: React,
  tagName: "md-elevated-button",
  elementClass: MdElevatedButtonElement,
  events: {},
});

export const MdFilledButton = createComponent({
  react: React,
  tagName: "md-filled-button",
  elementClass: MdFilledButtonElement,
  events: {},
});

export const MdFilledTonalButton = createComponent({
  react: React,
  tagName: "md-filled-tonal-button",
  elementClass: MdFilledTonalButtonElement,
  events: {},
});

export const MdOutlinedButton = createComponent({
  react: React,
  tagName: "md-outlined-button",
  elementClass: MdOutlinedButtonElement,
  events: {},
});

export const MdTextButton = createComponent({
  react: React,
  tagName: "md-text-button",
  elementClass: MdTextButtonElement,
  events: {},
});
