// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {M3Canvas3D as Md3dCanvasElement} from '@aphrody/material-web/canvas3d/canvas-3d.js';

export const Md3dCanvas = createComponent({
  react: React,
  tagName: 'md-3d-canvas',
  elementClass: Md3dCanvasElement,
  events: {},
});
