// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdCard as MdCardElement } from "@aphrody/material-web/card/card.js";

export const MdCard = createComponent({
  react: React,
  tagName: "md-card",
  elementClass: MdCardElement,
  events: {},
});
