// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { M3Card3D as Md3dCardElement } from "@aphrody-code/material-web/card3d/card-3d.js";

export const Md3dCard = createComponent({
  react: React,
  tagName: "md-3d-card",
  elementClass: Md3dCardElement,
  events: {},
});
