// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdCarousel as MdCarouselElement} from '@aphrody/material-web/carousel/carousel.js';
import {MdCarouselItem as MdCarouselItemElement} from '@aphrody/material-web/carousel/carousel-item.js';

export const MdCarousel = createComponent({
  react: React,
  tagName: 'md-carousel',
  elementClass: MdCarouselElement,
  events: {onChange: 'carousel-change'},
});

export const MdCarouselItem = createComponent({
  react: React,
  tagName: 'md-carousel-item',
  elementClass: MdCarouselItemElement,
  events: {},
});
