// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdLineChart as MdLineChartElement } from "@aphrody-code/material-web/charts/line-chart.js";
import { MdBarChart as MdBarChartElement } from "@aphrody-code/material-web/charts/bar-chart.js";
import { MdPieChart as MdPieChartElement } from "@aphrody-code/material-web/charts/pie-chart.js";
import { MdAreaChart as MdAreaChartElement } from "@aphrody-code/material-web/charts/area-chart.js";
import { MdSparkline as MdSparklineElement } from "@aphrody-code/material-web/charts/sparkline.js";
import { MdGauge as MdGaugeElement } from "@aphrody-code/material-web/charts/gauge.js";
import { MdScatterChart as MdScatterChartElement } from "@aphrody-code/material-web/charts/scatter-chart.js";
import { MdRadarChart as MdRadarChartElement } from "@aphrody-code/material-web/charts/radar-chart.js";

export const MdLineChart = createComponent({
  react: React,
  tagName: "md-line-chart",
  elementClass: MdLineChartElement,
  events: {},
});

export const MdBarChart = createComponent({
  react: React,
  tagName: "md-bar-chart",
  elementClass: MdBarChartElement,
  events: {},
});

export const MdPieChart = createComponent({
  react: React,
  tagName: "md-pie-chart",
  elementClass: MdPieChartElement,
  events: {},
});

export const MdAreaChart = createComponent({
  react: React,
  tagName: "md-area-chart",
  elementClass: MdAreaChartElement,
  events: {},
});

export const MdSparkline = createComponent({
  react: React,
  tagName: "md-sparkline",
  elementClass: MdSparklineElement,
  events: {},
});

export const MdGauge = createComponent({
  react: React,
  tagName: "md-gauge",
  elementClass: MdGaugeElement,
  events: {},
});

export const MdScatterChart = createComponent({
  react: React,
  tagName: "md-scatter-chart",
  elementClass: MdScatterChartElement,
  events: {},
});

export const MdRadarChart = createComponent({
  react: React,
  tagName: "md-radar-chart",
  elementClass: MdRadarChartElement,
  events: {},
});
