// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdCheckbox as MdCheckboxElement } from "@aphrody-code/material-web/checkbox/checkbox.js";

export const MdCheckbox = createComponent({
  react: React,
  tagName: "md-checkbox",
  elementClass: MdCheckboxElement,
  events: { onChange: "change", onInput: "input" },
});
