// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdAssistChip as MdAssistChipElement } from "@aphrody/material-web/chips/assist-chip.js";
import { MdChipSet as MdChipSetElement } from "@aphrody/material-web/chips/chip-set.js";
import { MdFilterChip as MdFilterChipElement } from "@aphrody/material-web/chips/filter-chip.js";
import { MdInputChip as MdInputChipElement } from "@aphrody/material-web/chips/input-chip.js";
import { MdSuggestionChip as MdSuggestionChipElement } from "@aphrody/material-web/chips/suggestion-chip.js";

export const MdAssistChip = createComponent({
  react: React,
  tagName: "md-assist-chip",
  elementClass: MdAssistChipElement,
  events: {},
});

export const MdChipSet = createComponent({
  react: React,
  tagName: "md-chip-set",
  elementClass: MdChipSetElement,
  events: {},
});

export const MdFilterChip = createComponent({
  react: React,
  tagName: "md-filter-chip",
  elementClass: MdFilterChipElement,
  events: {},
});

export const MdInputChip = createComponent({
  react: React,
  tagName: "md-input-chip",
  elementClass: MdInputChipElement,
  events: { onRemove: "remove", onUpdateFocus: "update-focus" },
});

export const MdSuggestionChip = createComponent({
  react: React,
  tagName: "md-suggestion-chip",
  elementClass: MdSuggestionChipElement,
  events: {},
});
