// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdDatePicker as MdDatePickerElement} from '@aphrody/material-web/datepicker/date-picker.js';
import {MdDateRangePicker as MdDateRangePickerElement} from '@aphrody/material-web/datepicker/date-range-picker.js';
import {MdDateTimePicker as MdDateTimePickerElement} from '@aphrody/material-web/datepicker/date-time-picker.js';

export const MdDatePicker = createComponent({
  react: React,
  tagName: 'md-date-picker',
  elementClass: MdDatePickerElement,
  events: {onChange: 'date-picker:change'},
});

export const MdDateRangePicker = createComponent({
  react: React,
  tagName: 'md-date-range-picker',
  elementClass: MdDateRangePickerElement,
  events: {onInput: 'input', onChange: 'change', onDateRangeChange: 'date-range-picker:change'},
});

export const MdDateTimePicker = createComponent({
  react: React,
  tagName: 'md-date-time-picker',
  elementClass: MdDateTimePickerElement,
  events: {onInput: 'input', onChange: 'change', onDateTimeChange: 'date-time-picker:change'},
});
