// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdDialog as MdDialogElement} from '@aphrody/material-web/dialog/dialog.js';

export const MdDialog = createComponent({
  react: React,
  tagName: 'md-dialog',
  elementClass: MdDialogElement,
  events: {onOpen: 'open', onOpened: 'opened', onClose: 'close', onClosed: 'closed', onCancel: 'cancel'},
});
