// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdDivider as MdDividerElement} from '@aphrody/material-web/divider/divider.js';

export const MdDivider = createComponent({
  react: React,
  tagName: 'md-divider',
  elementClass: MdDividerElement,
  events: {},
});
