// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdWebgpuCanvas as MdWebgpuCanvasElement} from '@aphrody/material-web/effects/webgpu-canvas.js';

export const MdWebgpuCanvas = createComponent({
  react: React,
  tagName: 'md-webgpu-canvas',
  elementClass: MdWebgpuCanvasElement,
  events: {},
});
