// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdElevation as MdElevationElement} from '@aphrody/material-web/elevation/elevation.js';

export const MdElevation = createComponent({
  react: React,
  tagName: 'md-elevation',
  elementClass: MdElevationElement,
  events: {},
});
