// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdAccordion as MdAccordionElement} from '@aphrody/material-web/expansion/accordion.js';
import {MdExpansionPanel as MdExpansionPanelElement} from '@aphrody/material-web/expansion/expansion-panel.js';

export const MdAccordion = createComponent({
  react: React,
  tagName: 'md-accordion',
  elementClass: MdAccordionElement,
  events: {},
});

export const MdExpansionPanel = createComponent({
  react: React,
  tagName: 'md-expansion-panel',
  elementClass: MdExpansionPanelElement,
  events: {onToggle: 'expansion:toggle'},
});
