// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdBrandedFab as MdBrandedFabElement } from "@aphrody/material-web/fab/branded-fab.js";
import { MdFab as MdFabElement } from "@aphrody/material-web/fab/fab.js";

export const MdBrandedFab = createComponent({
  react: React,
  tagName: "md-branded-fab",
  elementClass: MdBrandedFabElement,
  events: {},
});

export const MdFab = createComponent({
  react: React,
  tagName: "md-fab",
  elementClass: MdFabElement,
  events: {},
});
