// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdFabMenu as MdFabMenuElement } from "@aphrody-code/material-web/fabmenu/fab-menu.js";
import { MdFabMenuItem as MdFabMenuItemElement } from "@aphrody-code/material-web/fabmenu/fab-menu-item.js";

export const MdFabMenu = createComponent({
  react: React,
  tagName: "md-fab-menu",
  elementClass: MdFabMenuElement,
  events: { onOpen: "fab-menu:open", onClose: "fab-menu:close" },
});

export const MdFabMenuItem = createComponent({
  react: React,
  tagName: "md-fab-menu-item",
  elementClass: MdFabMenuItemElement,
  events: { onClick: "fab-menu-item:click" },
});
