// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdFilledField as MdFilledFieldElement } from "@aphrody/material-web/field/filled-field.js";
import { MdOutlinedField as MdOutlinedFieldElement } from "@aphrody/material-web/field/outlined-field.js";

export const MdFilledField = createComponent({
  react: React,
  tagName: "md-filled-field",
  elementClass: MdFilledFieldElement,
  events: {},
});

export const MdOutlinedField = createComponent({
  react: React,
  tagName: "md-outlined-field",
  elementClass: MdOutlinedFieldElement,
  events: {},
});
