// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdFocusRing as MdFocusRingElement} from '@aphrody/material-web/focus/md-focus-ring.js';

export const MdFocusRing = createComponent({
  react: React,
  tagName: 'md-focus-ring',
  elementClass: MdFocusRingElement,
  events: {},
});
