// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { M3Globe3D as Md3dGlobeElement } from "@aphrody-code/material-web/globe3d/globe-3d.js";

export const Md3dGlobe = createComponent({
  react: React,
  tagName: "md-3d-globe",
  elementClass: Md3dGlobeElement,
  events: {},
});
