// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdGridList as MdGridListElement} from '@aphrody/material-web/gridlist/grid-list.js';
import {MdGridTile as MdGridTileElement} from '@aphrody/material-web/gridlist/grid-tile.js';

export const MdGridList = createComponent({
  react: React,
  tagName: 'md-grid-list',
  elementClass: MdGridListElement,
  events: {},
});

export const MdGridTile = createComponent({
  react: React,
  tagName: 'md-grid-tile',
  elementClass: MdGridTileElement,
  events: {},
});
