// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdIcon as MdIconElement } from "@aphrody-code/material-web/icon/icon.js";

export const MdIcon = createComponent({
  react: React,
  tagName: "md-icon",
  elementClass: MdIconElement,
  events: {},
});
