// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdFilledIconButton as MdFilledIconButtonElement } from "@aphrody-code/material-web/iconbutton/filled-icon-button.js";
import { MdFilledTonalIconButton as MdFilledTonalIconButtonElement } from "@aphrody-code/material-web/iconbutton/filled-tonal-icon-button.js";
import { MdIconButton as MdIconButtonElement } from "@aphrody-code/material-web/iconbutton/icon-button.js";
import { MdOutlinedIconButton as MdOutlinedIconButtonElement } from "@aphrody-code/material-web/iconbutton/outlined-icon-button.js";

export const MdFilledIconButton = createComponent({
  react: React,
  tagName: "md-filled-icon-button",
  elementClass: MdFilledIconButtonElement,
  events: {},
});

export const MdFilledTonalIconButton = createComponent({
  react: React,
  tagName: "md-filled-tonal-icon-button",
  elementClass: MdFilledTonalIconButtonElement,
  events: {},
});

export const MdIconButton = createComponent({
  react: React,
  tagName: "md-icon-button",
  elementClass: MdIconButtonElement,
  events: {},
});

export const MdOutlinedIconButton = createComponent({
  react: React,
  tagName: "md-outlined-icon-button",
  elementClass: MdOutlinedIconButtonElement,
  events: {},
});
