// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { Button as MdButtonElement } from "@aphrody-code/material-web/labs/gb/components/button/md-button.js";
import { MdElevatedCard as MdElevatedCardElement } from "@aphrody-code/material-web/labs/card/elevated-card.js";
import { MdFilledCard as MdFilledCardElement } from "@aphrody-code/material-web/labs/card/filled-card.js";
import { MdItem as MdItemElement } from "@aphrody-code/material-web/labs/item/item.js";
import { MenuGroup as MdMenuGroupElement } from "@aphrody-code/material-web/labs/gb/components/menu/md-menu-group.js";
import { MdNavigationBar as MdNavigationBarElement } from "@aphrody-code/material-web/labs/navigationbar/navigation-bar.js";
import { MdNavigationDrawer as MdNavigationDrawerElement } from "@aphrody-code/material-web/labs/navigationdrawer/navigation-drawer.js";
import { MdNavigationDrawerModal as MdNavigationDrawerModalElement } from "@aphrody-code/material-web/labs/navigationdrawer/navigation-drawer-modal.js";
import { MdNavigationTab as MdNavigationTabElement } from "@aphrody-code/material-web/labs/navigationtab/navigation-tab.js";
import { MdOutlinedCard as MdOutlinedCardElement } from "@aphrody-code/material-web/labs/card/outlined-card.js";
import { MdOutlinedSegmentedButton as MdOutlinedSegmentedButtonElement } from "@aphrody-code/material-web/labs/segmentedbutton/outlined-segmented-button.js";
import { MdOutlinedSegmentedButtonSet as MdOutlinedSegmentedButtonSetElement } from "@aphrody-code/material-web/labs/segmentedbuttonset/outlined-segmented-button-set.js";
import { SplitButton as MdSplitButtonElement } from "@aphrody-code/material-web/labs/gb/components/splitbutton/md-split-button.js";

export const MdButton = createComponent({
  react: React,
  tagName: "md-button",
  elementClass: MdButtonElement,
  events: {},
});

export const MdElevatedCard = createComponent({
  react: React,
  tagName: "md-elevated-card",
  elementClass: MdElevatedCardElement,
  events: {},
});

export const MdFilledCard = createComponent({
  react: React,
  tagName: "md-filled-card",
  elementClass: MdFilledCardElement,
  events: {},
});

export const MdItem = createComponent({
  react: React,
  tagName: "md-item",
  elementClass: MdItemElement,
  events: {},
});

export const MdMenuGroup = createComponent({
  react: React,
  tagName: "md-menu-group",
  elementClass: MdMenuGroupElement,
  events: {},
});

export const MdNavigationBar = createComponent({
  react: React,
  tagName: "md-navigation-bar",
  elementClass: MdNavigationBarElement,
  events: { onActivated: "navigation-bar-activated" },
});

export const MdNavigationDrawer = createComponent({
  react: React,
  tagName: "md-navigation-drawer",
  elementClass: MdNavigationDrawerElement,
  events: { onNavigationDrawerChanged: "navigation-drawer-changed" },
});

export const MdNavigationDrawerModal = createComponent({
  react: React,
  tagName: "md-navigation-drawer-modal",
  elementClass: MdNavigationDrawerModalElement,
  events: { onNavigationDrawerChanged: "navigation-drawer-changed" },
});

export const MdNavigationTab = createComponent({
  react: React,
  tagName: "md-navigation-tab",
  elementClass: MdNavigationTabElement,
  events: {},
});

export const MdOutlinedCard = createComponent({
  react: React,
  tagName: "md-outlined-card",
  elementClass: MdOutlinedCardElement,
  events: {},
});

export const MdOutlinedSegmentedButton = createComponent({
  react: React,
  tagName: "md-outlined-segmented-button",
  elementClass: MdOutlinedSegmentedButtonElement,
  events: {},
});

export const MdOutlinedSegmentedButtonSet = createComponent({
  react: React,
  tagName: "md-outlined-segmented-button-set",
  elementClass: MdOutlinedSegmentedButtonSetElement,
  events: {},
});

export const MdSplitButton = createComponent({
  react: React,
  tagName: "md-split-button",
  elementClass: MdSplitButtonElement,
  events: {},
});
