// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdListDetail as MdListDetailElement} from '@aphrody/material-web/layout/md-list-detail.js';
import {MdPane as MdPaneElement} from '@aphrody/material-web/layout/md-pane.js';
import {MdScaffold as MdScaffoldElement} from '@aphrody/material-web/layout/md-scaffold.js';
import {MdSupportingPane as MdSupportingPaneElement} from '@aphrody/material-web/layout/md-supporting-pane.js';

export const MdListDetail = createComponent({
  react: React,
  tagName: 'md-list-detail',
  elementClass: MdListDetailElement,
  events: {},
});

export const MdPane = createComponent({
  react: React,
  tagName: 'md-pane',
  elementClass: MdPaneElement,
  events: {},
});

export const MdScaffold = createComponent({
  react: React,
  tagName: 'md-scaffold',
  elementClass: MdScaffoldElement,
  events: {},
});

export const MdSupportingPane = createComponent({
  react: React,
  tagName: 'md-supporting-pane',
  elementClass: MdSupportingPaneElement,
  events: {},
});
