// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdLink as MdLinkElement } from "@aphrody/material-web/link/link.js";

export const MdLink = createComponent({
  react: React,
  tagName: "md-link",
  elementClass: MdLinkElement,
  events: {},
});
