// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdList as MdListElement } from "@aphrody-code/material-web/list/list.js";
import { MdListItem as MdListItemElement } from "@aphrody-code/material-web/list/list-item.js";

export const MdList = createComponent({
  react: React,
  tagName: "md-list",
  elementClass: MdListElement,
  events: {},
});

export const MdListItem = createComponent({
  react: React,
  tagName: "md-list-item",
  elementClass: MdListItemElement,
  events: {},
});
