// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdLoadingIndicator as MdLoadingIndicatorElement} from '@aphrody/material-web/loadingindicator/loading-indicator.js';

export const MdLoadingIndicator = createComponent({
  react: React,
  tagName: 'md-loading-indicator',
  elementClass: MdLoadingIndicatorElement,
  events: {},
});
