// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdMenu as MdMenuElement } from "@aphrody-code/material-web/menu/menu.js";
import { MdMenuItem as MdMenuItemElement } from "@aphrody-code/material-web/menu/menu-item.js";
import { MdSubMenu as MdSubMenuElement } from "@aphrody-code/material-web/menu/sub-menu.js";

export const MdMenu = createComponent({
  react: React,
  tagName: "md-menu",
  elementClass: MdMenuElement,
  events: { onOpening: "opening", onOpened: "opened", onClosing: "closing", onClosed: "closed" },
});

export const MdMenuItem = createComponent({
  react: React,
  tagName: "md-menu-item",
  elementClass: MdMenuItemElement,
  events: { onCloseMenu: "close-menu" },
});

export const MdSubMenu = createComponent({
  react: React,
  tagName: "md-sub-menu",
  elementClass: MdSubMenuElement,
  events: { onOpening: "opening", onOpened: "opened", onClosing: "closing", onClosed: "closed" },
});
