// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdMobileStepper as MdMobileStepperElement} from '@aphrody/material-web/mobilestepper/mobile-stepper.js';

export const MdMobileStepper = createComponent({
  react: React,
  tagName: 'md-mobile-stepper',
  elementClass: MdMobileStepperElement,
  events: {},
});
