// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdNavigationRail as MdNavigationRailElement} from '@aphrody/material-web/navigationrail/navigation-rail.js';
import {MdNavigationRailItem as MdNavigationRailItemElement} from '@aphrody/material-web/navigationrail/navigation-rail-item.js';

export const MdNavigationRail = createComponent({
  react: React,
  tagName: 'md-navigation-rail',
  elementClass: MdNavigationRailElement,
  events: {onChange: 'navigation-rail:change', onItemActivate: 'navigation-rail-item:activate'},
});

export const MdNavigationRailItem = createComponent({
  react: React,
  tagName: 'md-navigation-rail-item',
  elementClass: MdNavigationRailItemElement,
  events: {},
});
