// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdPaginator as MdPaginatorElement} from '@aphrody/material-web/paginator/paginator.js';

export const MdPaginator = createComponent({
  react: React,
  tagName: 'md-paginator',
  elementClass: MdPaginatorElement,
  events: {onPage: 'paginator:page'},
});
