// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdPopover as MdPopoverElement } from "@aphrody/material-web/popover/popover.js";

export const MdPopover = createComponent({
  react: React,
  tagName: "md-popover",
  elementClass: MdPopoverElement,
  events: { onOpened: "opened", onClosed: "closed" },
});
