// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdCircularProgress as MdCircularProgressElement} from '@aphrody/material-web/progress/circular-progress.js';
import {MdLinearProgress as MdLinearProgressElement} from '@aphrody/material-web/progress/linear-progress.js';

export const MdCircularProgress = createComponent({
  react: React,
  tagName: 'md-circular-progress',
  elementClass: MdCircularProgressElement,
  events: {},
});

export const MdLinearProgress = createComponent({
  react: React,
  tagName: 'md-linear-progress',
  elementClass: MdLinearProgressElement,
  events: {},
});
