// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdRadio as MdRadioElement } from "@aphrody/material-web/radio/radio.js";

export const MdRadio = createComponent({
  react: React,
  tagName: "md-radio",
  elementClass: MdRadioElement,
  events: { onChange: "change", onInput: "input" },
});
