// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdRating as MdRatingElement } from "@aphrody/material-web/rating/rating.js";

export const MdRating = createComponent({
  react: React,
  tagName: "md-rating",
  elementClass: MdRatingElement,
  events: { onChange: "change", onInput: "input" },
});
