// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdRipple as MdRippleElement } from "@aphrody/material-web/ripple/ripple.js";

export const MdRipple = createComponent({
  react: React,
  tagName: "md-ripple",
  elementClass: MdRippleElement,
  events: {},
});
