// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdScheduler as MdSchedulerElement} from '@aphrody/material-web/scheduler/scheduler.js';

export const MdScheduler = createComponent({
  react: React,
  tagName: 'md-scheduler',
  elementClass: MdSchedulerElement,
  events: {onNavigate: 'scheduler:navigate', onSelect: 'scheduler:select', onEventClick: 'scheduler:event-click'},
});
