// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdSearchBar as MdSearchBarElement } from "@aphrody/material-web/search/search-bar.js";

export const MdSearchBar = createComponent({
  react: React,
  tagName: "md-search-bar",
  elementClass: MdSearchBarElement,
  events: {
    onInput: "input",
    onSearch: "search",
    onSearchOpen: "search:open",
    onSearchClose: "search:close",
  },
});
