// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdFilledSelect as MdFilledSelectElement } from "@aphrody-code/material-web/select/filled-select.js";
import { MdOutlinedSelect as MdOutlinedSelectElement } from "@aphrody-code/material-web/select/outlined-select.js";
import { MdSelectOption as MdSelectOptionElement } from "@aphrody-code/material-web/select/select-option.js";

export const MdFilledSelect = createComponent({
  react: React,
  tagName: "md-filled-select",
  elementClass: MdFilledSelectElement,
  events: {
    onChange: "change",
    onInput: "input",
    onOpening: "opening",
    onOpened: "opened",
    onClosing: "closing",
    onClosed: "closed",
  },
});

export const MdOutlinedSelect = createComponent({
  react: React,
  tagName: "md-outlined-select",
  elementClass: MdOutlinedSelectElement,
  events: {
    onChange: "change",
    onInput: "input",
    onOpening: "opening",
    onOpened: "opened",
    onClosing: "closing",
    onClosed: "closed",
  },
});

export const MdSelectOption = createComponent({
  react: React,
  tagName: "md-select-option",
  elementClass: MdSelectOptionElement,
  events: {},
});
