// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdBottomSheet as MdBottomSheetElement} from '@aphrody/material-web/sheet/bottom-sheet.js';
import {MdSideSheet as MdSideSheetElement} from '@aphrody/material-web/sheet/side-sheet.js';

export const MdBottomSheet = createComponent({
  react: React,
  tagName: 'md-bottom-sheet',
  elementClass: MdBottomSheetElement,
  events: {onOpening: 'bottom-sheet:opening', onOpened: 'bottom-sheet:opened', onClosing: 'bottom-sheet:closing', onClosed: 'bottom-sheet:closed'},
});

export const MdSideSheet = createComponent({
  react: React,
  tagName: 'md-side-sheet',
  elementClass: MdSideSheetElement,
  events: {onOpening: 'side-sheet:opening', onOpened: 'side-sheet:opened', onClosing: 'side-sheet:closing', onClosed: 'side-sheet:closed'},
});
