// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdSkeleton as MdSkeletonElement } from "@aphrody/material-web/skeleton/skeleton.js";

export const MdSkeleton = createComponent({
  react: React,
  tagName: "md-skeleton",
  elementClass: MdSkeletonElement,
  events: {},
});
