// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdSlider as MdSliderElement } from "@aphrody/material-web/slider/slider.js";

export const MdSlider = createComponent({
  react: React,
  tagName: "md-slider",
  elementClass: MdSliderElement,
  events: { onChange: "change", onInput: "input" },
});
