// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdSnackbar as MdSnackbarElement} from '@aphrody/material-web/snackbar/snackbar.js';

export const MdSnackbar = createComponent({
  react: React,
  tagName: 'md-snackbar',
  elementClass: MdSnackbarElement,
  events: {onOpening: 'opening', onOpened: 'opened', onClosing: 'closing', onClosed: 'closed'},
});
