// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdStep as MdStepElement} from '@aphrody/material-web/stepper/step.js';
import {MdStepper as MdStepperElement} from '@aphrody/material-web/stepper/stepper.js';

export const MdStep = createComponent({
  react: React,
  tagName: 'md-step',
  elementClass: MdStepElement,
  events: {},
});

export const MdStepper = createComponent({
  react: React,
  tagName: 'md-stepper',
  elementClass: MdStepperElement,
  events: {onChange: 'stepper:change'},
});
