// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdSurface as MdSurfaceElement} from '@aphrody/material-web/surface/surface.js';

export const MdSurface = createComponent({
  react: React,
  tagName: 'md-surface',
  elementClass: MdSurfaceElement,
  events: {},
});
