// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdSwitch as MdSwitchElement } from "@aphrody/material-web/switch/switch.js";

export const MdSwitch = createComponent({
  react: React,
  tagName: "md-switch",
  elementClass: MdSwitchElement,
  events: { onChange: "change", onInput: "input" },
});
