// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdTable as MdTableElement } from "@aphrody/material-web/table/table.js";

export const MdTable = createComponent({
  react: React,
  tagName: "md-table",
  elementClass: MdTableElement,
  events: { onSort: "table:sort", onSelectionChange: "table:selection-change" },
});
