// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdPrimaryTab as MdPrimaryTabElement } from "@aphrody/material-web/tabs/primary-tab.js";
import { MdSecondaryTab as MdSecondaryTabElement } from "@aphrody/material-web/tabs/secondary-tab.js";
import { MdTabs as MdTabsElement } from "@aphrody/material-web/tabs/tabs.js";

export const MdPrimaryTab = createComponent({
  react: React,
  tagName: "md-primary-tab",
  elementClass: MdPrimaryTabElement,
  events: {},
});

export const MdSecondaryTab = createComponent({
  react: React,
  tagName: "md-secondary-tab",
  elementClass: MdSecondaryTabElement,
  events: {},
});

export const MdTabs = createComponent({
  react: React,
  tagName: "md-tabs",
  elementClass: MdTabsElement,
  events: { onChange: "change" },
});
