// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdFilledTextField as MdFilledTextFieldElement} from '@aphrody/material-web/textfield/filled-text-field.js';
import {MdOutlinedTextField as MdOutlinedTextFieldElement} from '@aphrody/material-web/textfield/outlined-text-field.js';

export const MdFilledTextField = createComponent({
  react: React,
  tagName: 'md-filled-text-field',
  elementClass: MdFilledTextFieldElement,
  events: {onChange: 'change', onInput: 'input'},
});

export const MdOutlinedTextField = createComponent({
  react: React,
  tagName: 'md-outlined-text-field',
  elementClass: MdOutlinedTextFieldElement,
  events: {onChange: 'change', onInput: 'input'},
});
