// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdTimePicker as MdTimePickerElement } from "@aphrody/material-web/timepicker/time-picker.js";

export const MdTimePicker = createComponent({
  react: React,
  tagName: "md-time-picker",
  elementClass: MdTimePickerElement,
  events: { onChange: "time-picker:change" },
});
