// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from 'react';
import {createComponent} from '@lit/react';

import {MdTooltip as MdTooltipElement} from '@aphrody/material-web/tooltip/tooltip.js';

export const MdTooltip = createComponent({
  react: React,
  tagName: 'md-tooltip',
  elementClass: MdTooltipElement,
  events: {onShow: 'tooltip-show', onHide: 'tooltip-hide'},
});
