// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdToolbar as MdToolbarElement } from "@aphrody-code/material-web/toolbar/md-toolbar.js";

export const MdToolbar = createComponent({
  react: React,
  tagName: "md-toolbar",
  elementClass: MdToolbarElement,
  events: {},
});
