// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdTree as MdTreeElement } from "@aphrody-code/material-web/tree/tree.js";
import { MdTreeItem as MdTreeItemElement } from "@aphrody-code/material-web/tree/tree-item.js";

export const MdTree = createComponent({
  react: React,
  tagName: "md-tree",
  elementClass: MdTreeElement,
  events: { onSelect: "tree:select" },
});

export const MdTreeItem = createComponent({
  react: React,
  tagName: "md-tree-item",
  elementClass: MdTreeItemElement,
  events: { onToggle: "tree-item:toggle", onActivate: "tree-item:activate" },
});
