// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdType as MdTypeElement } from "@aphrody-code/material-web/typography/md-type.js";

export const MdType = createComponent({
  react: React,
  tagName: "md-type",
  elementClass: MdTypeElement,
  events: {},
});
