// AUTO-GENERATED by generate.ts — do not edit by hand. Run `bun run generate`.

import * as React from "react";
import { createComponent } from "@lit/react";

import { MdVirtualScroller as MdVirtualScrollerElement } from "@aphrody/material-web/virtualscroll/virtual-scroller.js";

export const MdVirtualScroller = createComponent({
  react: React,
  tagName: "md-virtual-scroller",
  elementClass: MdVirtualScrollerElement,
  events: { onRange: "virtual-scroll:range" },
});
