// SPDX-License-Identifier: Apache-2.0
//! Détection et purge des marqueurs IA, signatures, et émoji.
//!
//! La règle est sèche : aucune mention d'outil IA ne survit à un passage de
//! `scrub()`. Les commentaires entièrement composés de signature sont marqués
//! `Drop` et seront retirés du fichier ; les autres voient juste la signature
//! enlevée.

use std::sync::OnceLock;

use regex::Regex;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Keep,
    Scrub,
    Drop,
}

static PATTERNS_DROP_WHOLE: OnceLock<Vec<Regex>> = OnceLock::new();
static PATTERNS_SCRUB: OnceLock<Vec<Regex>> = OnceLock::new();
static RE_EMOJI: OnceLock<Regex> = OnceLock::new();

fn patterns_drop_whole() -> &'static Vec<Regex> {
    PATTERNS_DROP_WHOLE.get_or_init(|| {
        // Lignes entières qui ne sont QUE de la signature/attribution AI.
        let raw = [
            r"(?i)^\s*🤖\s*generated with\s*\[?claude code\]?",
            r"(?i)^\s*generated with\s*\[?claude code\]?",
            r"(?i)^\s*co-authored-by:\s*claude",
            r"(?i)^\s*co-authored-by:\s*gpt",
            r"(?i)^\s*co-authored-by:\s*gemini",
            r"(?i)^\s*co-authored-by:\s*copilot",
            r"(?i)^\s*written\s+(by|with)\s+(an?\s+)?ai",
            r"(?i)^\s*assisted\s+by\s+(an?\s+)?ai",
            r"(?i)^\s*generated\s+by\s+(an?\s+)?ai",
            r"(?i)^\s*made\s+with\s+(an?\s+)?ai",
            r"(?i)^\s*ai[- ]?(generated|assisted|created)",
            r"(?i)^\s*\[?\s*(claude|gpt|gemini|copilot|anthropic|openai)\s+(generated|assist|wrote)\]?",
        ];
        raw.iter().map(|p| Regex::new(p).expect("regex compiles")).collect()
    })
}

fn patterns_scrub() -> &'static Vec<Regex> {
    PATTERNS_SCRUB.get_or_init(|| {
        // Fragments à retirer du corps tout en gardant le reste.
        let raw = [
            r"(?i)🤖\s*generated with\s*\[?claude code\]?(\(https?://[^)]*\))?",
            r"(?i)generated with\s*\[?claude code\]?(\(https?://[^)]*\))?",
            r"(?i)co-authored-by:\s*(claude|gpt|gemini|copilot)[^\n]*",
            r"(?i)\(generated by ai\)",
            r"(?i)\bai[- ]?(generated|assisted|created)\b",
            r"(?i)\bwith help from (claude|gpt|gemini|copilot|chatgpt|anthropic|openai)\b",
            r"(?i)\bclaude code\b",
            r"(?i)\bcursor ai\b",
            r"(?i)\bgithub copilot\b",
            r"(?i)\baphrody is fan of byron\b",
        ];
        raw.iter().map(|p| Regex::new(p).expect("regex compiles")).collect()
    })
}

fn re_emoji() -> &'static Regex {
    RE_EMOJI.get_or_init(|| {
        // Plages Unicode des émoji et pictogrammes. Garde la ponctuation ASCII.
        Regex::new(concat!(
            r"[\u{1F300}-\u{1F5FF}]|",
            r"[\u{1F600}-\u{1F64F}]|",
            r"[\u{1F680}-\u{1F6FF}]|",
            r"[\u{1F700}-\u{1F77F}]|",
            r"[\u{1F780}-\u{1F7FF}]|",
            r"[\u{1F800}-\u{1F8FF}]|",
            r"[\u{1F900}-\u{1F9FF}]|",
            r"[\u{1FA00}-\u{1FA6F}]|",
            r"[\u{1FA70}-\u{1FAFF}]|",
            r"[\u{2600}-\u{26FF}]|",
            r"[\u{2700}-\u{27BF}]|",
            r"\u{FE0F}|",
            r"[\u{1F1E6}-\u{1F1FF}]"
        ))
        .expect("regex compiles")
    })
}

pub fn classify(body: &str) -> Action {
    for re in patterns_drop_whole() {
        if re.is_match(body) {
            return Action::Drop;
        }
    }
    for re in patterns_scrub() {
        if re.is_match(body) {
            return Action::Scrub;
        }
    }
    if re_emoji().is_match(body) {
        return Action::Scrub;
    }
    Action::Keep
}

pub fn scrub(body: &str) -> String {
    let mut s = body.to_string();
    for re in patterns_scrub() {
        s = re.replace_all(&s, "").to_string();
    }
    s = re_emoji().replace_all(&s, "").to_string();
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn drop_full_signature() {
        let body = "🤖 Generated with [Claude Code](https://claude.com)";
        assert_eq!(classify(body), Action::Drop);
    }

    #[test]
    fn scrub_inline_mention() {
        let body = "This sorts the input with help from Claude.";
        assert_eq!(classify(body), Action::Scrub);
        assert_eq!(scrub(body), "This sorts the input .");
    }

    #[test]
    fn emoji_stripped() {
        assert_eq!(scrub("Init the server 🚀 now"), "Init the server now");
    }

    #[test]
    fn keep_clean() {
        assert_eq!(classify("Parse the buffer in place."), Action::Keep);
    }
}
