// SPDX-License-Identifier: Apache-2.0
//! aphrody-telemetry — in-process observability primitives for the aphrody runtime.
//!
//! Three primitives, modelled after the OpenTelemetry data model but without
//! pulling in any OTLP / gRPC / protobuf weight:
//!
//! * **Spans** — hierarchical timed work units with attributes, events, and a
//!   final [`SpanStatus`]. Parent/child links carry a [`TraceId`] so a whole
//!   call tree can be reconstructed from a flat dump.
//! * **Counters** — monotonic `u64` accumulators, thread-safe via `AtomicU64`,
//!   intended for "number of HTTP requests served" style metrics.
//! * **Histograms** — bucketed `f64` observations with a sum and count, useful
//!   for latency / request-size distributions. Buckets are caller-supplied
//!   upper bounds; an implicit `+inf` overflow bucket is *not* added, mirroring
//!   the strict OpenTelemetry explicit-bucket histogram contract.
//!
//! ## Cohesion with the wider workspace
//!
//! This crate intentionally complements three sibling crates without
//! overlapping their responsibilities:
//!
//! * **`aphrody-session`** owns the *conversation-level* JSONL log (one file
//!   per session, replayable via `from_jsonl`); telemetry here is the
//!   *operational* log (one append-only NDJSON stream per process run). They
//!   share the monotonic-id + atomic-write patterns but answer different
//!   questions ("what did the model say?" vs "how long did the call take?").
//! * **`aphrody-rateguard`** uses `parking_lot::Mutex` + `AtomicU64` for token
//!   buckets; we reuse the same primitives to keep the lock surface predictable
//!   under concurrent load.
//! * **`aphrody-cron`** writes job manifests with the tokio `tmp + flush + sync
//!   + rename` atomic pattern; we apply the same pattern to NDJSON span batches.
//!
//! ## Example
//!
//! ```no_run
//! use std::sync::Arc;
//! use aphrody_telemetry::{NdjsonSpanExporter, SpanKind, SpanStatus, Telemetry};
//!
//! # async fn run() -> Result<(), aphrody_telemetry::TelemetryError> {
//! let telemetry = Arc::new(Telemetry::new(1024));
//!
//! // Counters & histograms are free to register on the fly.
//! let requests = telemetry.counter("http.requests");
//! let latency  = telemetry.histogram("http.latency_ms", vec![1.0, 10.0, 100.0, 1_000.0]);
//!
//! // Hierarchical spans, RAII-finalized on drop.
//! let parent = telemetry.start_span("handle_request", SpanKind::Server, None);
//! let child  = telemetry.start_span("db.query", SpanKind::Client, Some(parent.id()));
//! child.set_attribute("db.system", "sqlite");
//! latency.observe(8.5);
//! requests.inc();
//! child.end(); // explicit close; otherwise Drop runs with status=Ok
//! parent.set_status(SpanStatus::Ok);
//! parent.end();
//!
//! // Drain & export to NDJSON.
//! let spans = telemetry.dump_spans();
//! NdjsonSpanExporter::new("./var/telemetry/spans.ndjson").export(&spans).await?;
//! # Ok(()) }
//! ```

#![forbid(unsafe_code)]

use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use chrono::{DateTime, Utc};
use parking_lot::{Mutex, RwLock};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::fs as afs;
use tokio::io::AsyncWriteExt;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// All recoverable failures emitted by this crate.
///
/// Shape modelled after `aphrody_session::SessionError` — opaque transparent
/// forwards for IO and JSON, named variants for domain errors.
#[derive(Debug, Error)]
pub enum TelemetryError {
    /// Filesystem error while exporting an NDJSON batch.
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    /// JSON serialization of a span failed.
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    /// `end()` was called twice on the same `SpanHandle`, or the underlying
    /// span was finalized through some other path before the handle dropped.
    #[error("span already ended")]
    SpanAlreadyEnded,
    /// `Telemetry::histogram` was called with an empty bucket list. Histograms
    /// require at least one upper bound, sorted ascending.
    #[error("histogram requires at least one bucket upper bound")]
    HistogramBucketsRequired,
}

// ---------------------------------------------------------------------------
// SpanId / TraceId — monotonic process-local newtypes
// ---------------------------------------------------------------------------

/// Process-local monotonic span identifier.
///
/// Generated by [`SpanId::generate`] from a single atomic counter; the first
/// id is always non-zero (the counter is seeded from the current wall clock
/// on first use).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SpanId(u64);

impl SpanId {
    /// Allocate a fresh, monotonically increasing identifier.
    #[must_use]
    pub fn generate() -> Self {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        seed_then_bump(&COUNTER)
    }

    /// Borrow the raw underlying `u64`.
    #[must_use]
    pub const fn as_u64(self) -> u64 {
        self.0
    }
}

impl fmt::Display for SpanId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "span-{:016x}", self.0)
    }
}

/// Process-local monotonic trace identifier.
///
/// Generated by [`TraceId::generate`] from a single atomic counter; carries no
/// hierarchical link by itself — every span in the same trace shares the same
/// `TraceId`, and parent/child relationships are encoded through
/// [`Span::parent`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TraceId(u64);

impl TraceId {
    /// Allocate a fresh, monotonically increasing identifier.
    #[must_use]
    pub fn generate() -> Self {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        seed_then_bump(&COUNTER)
    }

    /// Borrow the raw underlying `u64`.
    #[must_use]
    pub const fn as_u64(self) -> u64 {
        self.0
    }
}

impl fmt::Display for TraceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "trace-{:016x}", self.0)
    }
}

/// Helper that seeds the supplied counter from the wall clock on first use,
/// then returns `counter.fetch_add(1) + 1` wrapped in `T::from(u64)`.
fn seed_then_bump<T: From<u64>>(counter: &AtomicU64) -> T {
    let seed_from_clock: u64 = chrono::Utc::now()
        .timestamp_nanos_opt()
        .and_then(|n| u64::try_from(n).ok())
        .unwrap_or(1);
    let _ = counter.compare_exchange(
        0,
        seed_from_clock | 1,
        Ordering::Relaxed,
        Ordering::Relaxed,
    );
    let raw = counter.fetch_add(1, Ordering::Relaxed).wrapping_add(1);
    T::from(raw)
}

impl From<u64> for SpanId {
    fn from(v: u64) -> Self {
        Self(v)
    }
}

impl From<u64> for TraceId {
    fn from(v: u64) -> Self {
        Self(v)
    }
}

// ---------------------------------------------------------------------------
// SpanKind / SpanStatus / SpanEvent / Span
// ---------------------------------------------------------------------------

/// Classification of a span's role in the call chain.
///
/// Mirrors the OpenTelemetry [SpanKind] semantic conventions.
///
/// [SpanKind]: https://opentelemetry.io/docs/specs/otel/trace/api/#spankind
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SpanKind {
    /// Default — opaque local work (a function call, an internal job).
    Internal,
    /// Outbound call to a remote service.
    Client,
    /// Inbound call served to a remote caller.
    Server,
    /// Producer half of a message-queue exchange.
    Producer,
    /// Consumer half of a message-queue exchange.
    Consumer,
}

/// Final status assigned to a span before it is closed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "lowercase")]
pub enum SpanStatus {
    /// Status has not been set — typically the value carried by an in-flight
    /// span before the caller signals success or failure.
    Unset,
    /// Operation completed successfully.
    Ok,
    /// Operation failed; `message` carries a human-readable cause.
    Error {
        /// Human-readable cause of the failure.
        message: String,
    },
}

impl Default for SpanStatus {
    fn default() -> Self {
        Self::Unset
    }
}

/// A point-in-time event attached to a span.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SpanEvent {
    /// Wall-clock timestamp of when the event was recorded.
    pub ts: DateTime<Utc>,
    /// Event name (e.g. `cache.miss`, `retry.scheduled`).
    pub name: String,
    /// Free-form structured attributes attached to the event.
    #[serde(default)]
    pub attributes: HashMap<String, serde_json::Value>,
}

/// A finalized span ready for export. Lives entirely in memory; consumers
/// retrieve a copy via [`Telemetry::dump_spans`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Span {
    /// Stable, monotonic span identifier.
    pub id: SpanId,
    /// Owning trace; every span in the same logical operation shares this id.
    pub trace_id: TraceId,
    /// Parent span identifier; `None` marks the root span of a trace.
    #[serde(default)]
    pub parent: Option<SpanId>,
    /// Free-form name (the operation being timed).
    pub name: String,
    /// Classification of this span's role.
    pub kind: SpanKind,
    /// Wall-clock start.
    pub start: DateTime<Utc>,
    /// Wall-clock end — `None` while the span is still in-flight.
    #[serde(default)]
    pub end: Option<DateTime<Utc>>,
    /// Final status; defaults to [`SpanStatus::Unset`] for in-flight spans.
    #[serde(default)]
    pub status: SpanStatus,
    /// Free-form structured attributes.
    #[serde(default)]
    pub attributes: HashMap<String, serde_json::Value>,
    /// Ordered point-in-time events attached to this span.
    #[serde(default)]
    pub events: Vec<SpanEvent>,
}

impl Span {
    /// Wall-clock duration in milliseconds; `None` while the span is in-flight.
    #[must_use]
    pub fn duration_ms(&self) -> Option<u64> {
        self.end.map(|end| {
            let delta = end - self.start;
            let ms = delta.num_milliseconds();
            if ms < 0 { 0 } else { ms as u64 }
        })
    }

    /// Insert / overwrite a single attribute.
    pub fn set_attribute(&mut self, key: impl Into<String>, value: impl Into<serde_json::Value>) {
        self.attributes.insert(key.into(), value.into());
    }

    /// Append a structured event to this span. The timestamp is stamped from
    /// `Utc::now()` at append time.
    pub fn add_event(
        &mut self,
        name: impl Into<String>,
        attributes: HashMap<String, serde_json::Value>,
    ) {
        self.events.push(SpanEvent {
            ts: Utc::now(),
            name: name.into(),
            attributes,
        });
    }

    /// Close the span by stamping `end = Utc::now()` and assigning `status`.
    pub fn end_with_status(&mut self, status: SpanStatus) {
        self.end = Some(Utc::now());
        self.status = status;
    }

    /// Return `true` once `end` has been stamped.
    #[must_use]
    pub fn is_ended(&self) -> bool {
        self.end.is_some()
    }
}

// ---------------------------------------------------------------------------
// Counter
// ---------------------------------------------------------------------------

/// Monotonic `u64` accumulator. Thread-safe.
///
/// Created lazily via [`Telemetry::counter`] — repeated registrations of the
/// same name return the same `Arc<Counter>`, so producers and the exporter
/// observe the same underlying state.
#[derive(Debug)]
pub struct Counter {
    name: String,
    value: AtomicU64,
}

impl Counter {
    fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            value: AtomicU64::new(0),
        }
    }

    /// Counter name (immutable post-construction).
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Atomically increment by one.
    pub fn inc(&self) {
        self.value.fetch_add(1, Ordering::Relaxed);
    }

    /// Atomically add `n`.
    pub fn add(&self, n: u64) {
        self.value.fetch_add(n, Ordering::Relaxed);
    }

    /// Read the current value with `Relaxed` ordering.
    #[must_use]
    pub fn value(&self) -> u64 {
        self.value.load(Ordering::Relaxed)
    }
}

// ---------------------------------------------------------------------------
// Histogram
// ---------------------------------------------------------------------------

/// Bucketed `f64` observation distribution.
///
/// Bucket counts follow the strict OpenTelemetry explicit-bucket model: each
/// bucket `i` counts observations with `value <= buckets[i]`. Values greater
/// than every supplied upper bound are **not** counted in any bucket but still
/// contribute to `sum` and `count` (consistent with Prometheus semantics —
/// callers that want a `+inf` bucket should append `f64::INFINITY` themselves).
#[derive(Debug)]
pub struct Histogram {
    name: String,
    buckets: Vec<f64>,
    counts: Vec<AtomicU64>,
    sum_micros: AtomicU64,
    count: AtomicU64,
}

impl Histogram {
    fn new(name: impl Into<String>, buckets: Vec<f64>) -> Result<Self, TelemetryError> {
        if buckets.is_empty() {
            return Err(TelemetryError::HistogramBucketsRequired);
        }
        let counts = (0..buckets.len()).map(|_| AtomicU64::new(0)).collect();
        Ok(Self {
            name: name.into(),
            buckets,
            counts,
            sum_micros: AtomicU64::new(0),
            count: AtomicU64::new(0),
        })
    }

    /// Histogram name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Borrow the bucket upper bounds (caller-supplied at registration time).
    #[must_use]
    pub fn buckets(&self) -> &[f64] {
        &self.buckets
    }

    /// Record one observation. Values are routed to every bucket with
    /// `upper_bound >= value`, the global count is bumped, and the running sum
    /// is updated in microsecond fixed-point (×1_000_000) to dodge `f64`
    /// atomicity hazards.
    pub fn observe(&self, value: f64) {
        for (idx, &upper) in self.buckets.iter().enumerate() {
            if value <= upper {
                self.counts[idx].fetch_add(1, Ordering::Relaxed);
            }
        }
        self.count.fetch_add(1, Ordering::Relaxed);
        let micros = if value.is_finite() && value >= 0.0 {
            (value * 1_000_000.0) as u64
        } else {
            0
        };
        self.sum_micros.fetch_add(micros, Ordering::Relaxed);
    }

    /// Take a point-in-time snapshot of every counter. Cheap (one
    /// `Relaxed` load per bucket plus two more for sum + count).
    #[must_use]
    pub fn snapshot(&self) -> HistogramSnapshot {
        let bucket_counts = self
            .counts
            .iter()
            .map(|c| c.load(Ordering::Relaxed))
            .collect();
        let sum_micros = self.sum_micros.load(Ordering::Relaxed);
        HistogramSnapshot {
            name: self.name.clone(),
            buckets: self.buckets.clone(),
            bucket_counts,
            sum: (sum_micros as f64) / 1_000_000.0,
            count: self.count.load(Ordering::Relaxed),
        }
    }
}

/// Serializable point-in-time snapshot of a [`Histogram`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HistogramSnapshot {
    /// Histogram name.
    pub name: String,
    /// Bucket upper bounds (mirrors `Histogram::buckets`).
    pub buckets: Vec<f64>,
    /// Per-bucket cumulative counts; `bucket_counts[i]` counts every
    /// observation with `value <= buckets[i]`.
    pub bucket_counts: Vec<u64>,
    /// Sum of every observed value.
    pub sum: f64,
    /// Total number of observations.
    pub count: u64,
}

/// Serializable point-in-time snapshot of a [`Counter`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CounterSnapshot {
    /// Counter name.
    pub name: String,
    /// Current value.
    pub value: u64,
}

/// Roll-up of every metric currently registered with a [`Telemetry`] handle.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MetricsSnapshot {
    /// One [`CounterSnapshot`] per registered counter, sorted by name.
    pub counters: Vec<CounterSnapshot>,
    /// One [`HistogramSnapshot`] per registered histogram, sorted by name.
    pub histograms: Vec<HistogramSnapshot>,
}

// ---------------------------------------------------------------------------
// Telemetry — the top-level registry
// ---------------------------------------------------------------------------

/// Top-level handle that owns the span ring buffer plus the counter / histogram
/// registries. Cheap to clone via `Arc` — typical usage is a single
/// `Arc<Telemetry>` shared across the whole process.
#[derive(Debug)]
pub struct Telemetry {
    span_capacity: usize,
    spans: Mutex<Vec<Span>>,
    counters: RwLock<HashMap<String, Arc<Counter>>>,
    histograms: RwLock<HashMap<String, Arc<Histogram>>>,
}

impl Telemetry {
    /// Build a fresh handle backed by a ring buffer of `span_capacity` spans.
    /// When the buffer fills up, the oldest span is dropped to make room for
    /// the new one — caller is expected to drain via [`Telemetry::dump_spans`]
    /// + a [`NdjsonSpanExporter`] before that happens.
    ///
    /// A `span_capacity` of zero is normalized to 1.
    #[must_use]
    pub fn new(span_capacity: usize) -> Self {
        let cap = span_capacity.max(1);
        Self {
            span_capacity: cap,
            spans: Mutex::new(Vec::with_capacity(cap)),
            counters: RwLock::new(HashMap::new()),
            histograms: RwLock::new(HashMap::new()),
        }
    }

    /// Start a fresh in-flight span. The returned [`SpanHandle`] finalizes the
    /// span on `Drop` with `SpanStatus::Ok` if it has not already been ended.
    ///
    /// If `parent` is supplied, the new span inherits the parent's `TraceId`
    /// (if the parent can be located in the buffer); otherwise a fresh trace
    /// is opened.
    pub fn start_span(
        self: &Arc<Self>,
        name: impl Into<String>,
        kind: SpanKind,
        parent: Option<SpanId>,
    ) -> SpanHandle {
        let id = SpanId::generate();
        let trace_id = parent
            .and_then(|p| self.find_trace_for_span(p))
            .unwrap_or_else(TraceId::generate);
        let span = Span {
            id,
            trace_id,
            parent,
            name: name.into(),
            kind,
            start: Utc::now(),
            end: None,
            status: SpanStatus::Unset,
            attributes: HashMap::new(),
            events: Vec::new(),
        };
        {
            let mut guard = self.spans.lock();
            if guard.len() == self.span_capacity {
                // Drop the oldest span to make room.
                guard.remove(0);
            }
            guard.push(span);
        }
        SpanHandle {
            telemetry: Arc::clone(self),
            id,
            ended: false,
        }
    }

    /// Look up an existing span by id and return its `TraceId`.
    fn find_trace_for_span(&self, id: SpanId) -> Option<TraceId> {
        self.spans
            .lock()
            .iter()
            .find(|s| s.id == id)
            .map(|s| s.trace_id)
    }

    /// Look up or create the named counter. Repeated lookups of the same name
    /// return the same `Arc<Counter>`.
    pub fn counter(&self, name: impl Into<String>) -> Arc<Counter> {
        let name = name.into();
        // Fast path: already registered.
        if let Some(c) = self.counters.read().get(&name) {
            return Arc::clone(c);
        }
        // Slow path: register under the write lock; tolerate a race where two
        // callers raced past the fast-path read.
        let mut guard = self.counters.write();
        guard
            .entry(name.clone())
            .or_insert_with(|| Arc::new(Counter::new(name)))
            .clone()
    }

    /// Look up or create the named histogram with the supplied bucket bounds.
    ///
    /// # Errors
    ///
    /// Returns [`TelemetryError::HistogramBucketsRequired`] if `buckets` is
    /// empty.
    pub fn histogram(
        &self,
        name: impl Into<String>,
        buckets: Vec<f64>,
    ) -> Result<Arc<Histogram>, TelemetryError> {
        let name = name.into();
        if let Some(h) = self.histograms.read().get(&name) {
            return Ok(Arc::clone(h));
        }
        let mut guard = self.histograms.write();
        if let Some(h) = guard.get(&name) {
            return Ok(Arc::clone(h));
        }
        let h = Arc::new(Histogram::new(name.clone(), buckets)?);
        guard.insert(name, Arc::clone(&h));
        Ok(h)
    }

    /// Snapshot every span currently in the ring buffer.
    #[must_use]
    pub fn dump_spans(&self) -> Vec<Span> {
        self.spans.lock().clone()
    }

    /// Atomically drain the ring buffer, returning every recorded span and
    /// leaving the buffer empty. Useful before shutdown export.
    #[must_use]
    pub fn drain_spans(&self) -> Vec<Span> {
        let mut guard = self.spans.lock();
        std::mem::take(&mut *guard)
    }

    /// Snapshot every registered counter and histogram, sorted by name.
    #[must_use]
    pub fn dump_metrics(&self) -> MetricsSnapshot {
        let mut counters: Vec<CounterSnapshot> = self
            .counters
            .read()
            .values()
            .map(|c| CounterSnapshot {
                name: c.name().to_string(),
                value: c.value(),
            })
            .collect();
        counters.sort_by(|a, b| a.name.cmp(&b.name));
        let mut histograms: Vec<HistogramSnapshot> = self
            .histograms
            .read()
            .values()
            .map(|h| h.snapshot())
            .collect();
        histograms.sort_by(|a, b| a.name.cmp(&b.name));
        MetricsSnapshot {
            counters,
            histograms,
        }
    }

    /// Mutate an in-flight span identified by `id`. The closure runs under the
    /// span buffer lock — keep it short.
    fn with_span<R>(&self, id: SpanId, f: impl FnOnce(&mut Span) -> R) -> Option<R> {
        let mut guard = self.spans.lock();
        guard.iter_mut().find(|s| s.id == id).map(f)
    }
}

// ---------------------------------------------------------------------------
// SpanHandle — RAII closer for an in-flight span
// ---------------------------------------------------------------------------

/// RAII handle returned by [`Telemetry::start_span`].
///
/// The handle owns the right to finalize the underlying [`Span`]; dropping it
/// without calling [`SpanHandle::end`] finalizes with [`SpanStatus::Ok`].
///
/// All mutator methods are no-ops once the underlying span has been ended.
#[derive(Debug)]
pub struct SpanHandle {
    telemetry: Arc<Telemetry>,
    id: SpanId,
    ended: bool,
}

impl SpanHandle {
    /// Borrow this handle's span id (useful as a `parent` argument for
    /// subsequent child spans).
    #[must_use]
    pub fn id(&self) -> SpanId {
        self.id
    }

    /// Insert / overwrite an attribute on the underlying span.
    pub fn set_attribute(
        &self,
        key: impl Into<String>,
        value: impl Into<serde_json::Value>,
    ) -> &Self {
        let key = key.into();
        let value = value.into();
        let _ = self.telemetry.with_span(self.id, |s| {
            s.attributes.insert(key, value);
        });
        self
    }

    /// Append a structured event to the underlying span.
    pub fn add_event(
        &self,
        name: impl Into<String>,
        attributes: HashMap<String, serde_json::Value>,
    ) -> &Self {
        let name = name.into();
        let _ = self.telemetry.with_span(self.id, |s| {
            s.add_event(name, attributes);
        });
        self
    }

    /// Assign a non-final status. The status sticks if `end()` is later called
    /// without an explicit override.
    pub fn set_status(&self, status: SpanStatus) -> &Self {
        let _ = self.telemetry.with_span(self.id, |s| {
            s.status = status;
        });
        self
    }

    /// Explicitly close the underlying span with the currently-assigned
    /// status, falling back to [`SpanStatus::Ok`] if none was set. After this
    /// call, every other mutator is a no-op and `Drop` will not double-close.
    pub fn end(mut self) {
        self.finalize_with(None);
    }

    /// Internal: finalize with `status_override` if supplied, else promote
    /// `Unset` to `Ok`.
    fn finalize_with(&mut self, status_override: Option<SpanStatus>) {
        if self.ended {
            return;
        }
        self.ended = true;
        let _ = self.telemetry.with_span(self.id, |s| {
            if s.is_ended() {
                return;
            }
            let final_status = status_override.unwrap_or_else(|| match &s.status {
                SpanStatus::Unset => SpanStatus::Ok,
                other => other.clone(),
            });
            s.end_with_status(final_status);
        });
    }
}

impl Drop for SpanHandle {
    fn drop(&mut self) {
        if !self.ended {
            self.finalize_with(None);
        }
    }
}

// ---------------------------------------------------------------------------
// NdjsonSpanExporter — append-only file sink
// ---------------------------------------------------------------------------

/// Append-only NDJSON file exporter.
///
/// Every call to [`NdjsonSpanExporter::export`] serializes the supplied spans
/// to a UTF-8 buffer (one JSON object per line), then writes them through a
/// `tmp + flush + sync + rename`-style flow that mirrors
/// `aphrody_cron::JsonFileJobStore` and `aphrody_session::JsonlFileStore`.
/// Unlike those crates, *append* semantics are preserved: existing content is
/// read, the new payload is concatenated, and the result is rewritten
/// atomically. That trades raw throughput for crash-safety, which is the
/// right call for a telemetry sink.
#[derive(Debug, Clone)]
pub struct NdjsonSpanExporter {
    path: PathBuf,
}

impl NdjsonSpanExporter {
    /// Build a new exporter rooted at `path`. The parent directory is created
    /// on first export — `new` itself never touches the filesystem.
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into() }
    }

    /// Borrow the backing file path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Serialize `spans` to NDJSON and append them to the backing file.
    ///
    /// # Errors
    ///
    /// Returns [`TelemetryError::Json`] if any span fails to serialize and
    /// [`TelemetryError::Io`] for any filesystem failure.
    pub async fn export(&self, spans: &[Span]) -> Result<(), TelemetryError> {
        if spans.is_empty() {
            return Ok(());
        }
        // Serialize first so we don't touch the filesystem if encoding fails.
        let mut payload = String::new();
        for s in spans {
            let line = serde_json::to_string(s)?;
            payload.push_str(&line);
            payload.push('\n');
        }
        if let Some(parent) = self.path.parent() {
            if !parent.as_os_str().is_empty() {
                afs::create_dir_all(parent).await?;
            }
        }
        // Read the existing file (if any) and concatenate. Atomic rewrite via
        // tmp + flush + sync + rename so concurrent readers never see a torn
        // file.
        let existing = match afs::read(&self.path).await {
            Ok(b) => b,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Vec::new(),
            Err(e) => return Err(e.into()),
        };
        let tmp = self.path.with_extension("ndjson.tmp");
        {
            let mut f = afs::File::create(&tmp).await?;
            if !existing.is_empty() {
                f.write_all(&existing).await?;
                if !existing.ends_with(b"\n") {
                    f.write_all(b"\n").await?;
                }
            }
            f.write_all(payload.as_bytes()).await?;
            f.flush().await?;
            f.sync_all().await?;
        }
        afs::rename(&tmp, &self.path).await?;
        tracing::debug!(
            target: "aphrody_telemetry",
            path = %self.path.display(),
            count = spans.len(),
            "ndjson span batch exported",
        );
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// In-crate unit tests (additional smoke coverage lives under tests/)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn span_id_display_format() {
        let id = SpanId::from(0xdead_beef_u64);
        assert_eq!(id.to_string(), "span-00000000deadbeef");
    }

    #[test]
    fn trace_id_display_format() {
        let id = TraceId::from(0xcafe_u64);
        assert_eq!(id.to_string(), "trace-000000000000cafe");
    }

    #[test]
    fn telemetry_new_zero_capacity_is_normalized_to_one() {
        let t = Arc::new(Telemetry::new(0));
        let h = t.start_span("only", SpanKind::Internal, None);
        h.end();
        assert_eq!(t.dump_spans().len(), 1);
    }

    #[test]
    fn histogram_requires_buckets() {
        let t = Telemetry::new(8);
        let r = t.histogram("nope", Vec::new());
        assert!(matches!(r, Err(TelemetryError::HistogramBucketsRequired)));
    }

    #[test]
    fn counter_is_shared_across_lookups() {
        let t = Telemetry::new(8);
        let a = t.counter("shared");
        let b = t.counter("shared");
        a.inc();
        b.inc();
        assert_eq!(a.value(), 2);
        assert_eq!(b.value(), 2);
    }
}
