[package]
name = "aphrody-summary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "aphrody_summary"
path = "src/lib.rs"

[[bin]]
name = "aphrody-summary"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
