// SPDX-License-Identifier: Apache-2.0
//! `aphrody design tokens` — emit Material 3 color tokens as CSS or as a
//! shadcn/ui `registry:theme` item.
//!
//! Backs the UI fusion (see `docs/design/FUSION-PLAN.md` /
//! `docs/design/FUSION-STEP2-PLAN.md`): a headless, 100%-Rust generator.
//! - `--format css` (default): the M3 `--md-sys-color-*` `:root` block, plus the shadcn + Tailwind
//!   v4 alias sheets when `--fusion` is set.
//! - `--format shadcn-registry`: a `registry:theme` item (JSON) whose `cssVars.theme` aliases
//!   shadcn tokens to `var(--md-sys-color-*)` and whose `cssVars.light`/`dark` carry the M3 palette
//!   — consumable via `shadcn add`.

use crate::{DesignActions, TokensFormat};

/// Dispatch the `design` subcommand.
pub(crate) fn run(action: DesignActions) -> miette::Result<()> {
    match action {
        DesignActions::Tokens { format, fusion, dark, output } => {
            tokens(&format, fusion, dark, output)
        },
    }
}

/// Emit M3 color tokens in the requested format to a file or stdout.
fn tokens(
    format: &TokensFormat,
    fusion: bool,
    dark: bool,
    output: Option<std::path::PathBuf>,
) -> miette::Result<()> {
    let payload = match format {
        TokensFormat::Css => css(fusion, dark),
        TokensFormat::ShadcnRegistry => shadcn_registry_theme()?,
    };

    match output {
        Some(path) => {
            std::fs::write(&path, payload.as_bytes())
                .map_err(|e| miette::miette!("write {}: {e}", path.display()))?;
            println!("wrote {}", path.display());
        },
        None => println!("{payload}"),
    }
    Ok(())
}

/// Raw CSS custom properties (optionally the full fusion stylesheet).
fn css(fusion: bool, dark: bool) -> String {
    use m3_tokens::color::{BASELINE, BASELINE_DARK, export_css, export_fusion_css};
    let theme = if dark { &BASELINE_DARK } else { &BASELINE };
    if fusion { export_fusion_css(theme) } else { export_css(theme) }
}

/// Build the shadcn/ui `registry:theme` item JSON from the M3 palette.
fn shadcn_registry_theme() -> miette::Result<String> {
    use m3_tokens::color::{BASELINE, BASELINE_DARK, FUSION_ALIAS_MAP, color_vars};
    use serde_json::{Map, Value, json};

    // cssVars.theme: shadcn semantic tokens aliased to the M3 system colors
    // (mode-independent — emitted to :root).
    let mut theme = Map::new();
    for (name, role) in FUSION_ALIAS_MAP {
        theme
            .insert((*name).to_string(), Value::String(std::format!("var(--md-sys-color-{role})")));
    }

    // cssVars.light / .dark: the M3 palette itself (`--md-sys-color-*`).
    let palette = |theme: &m3_tokens::color::ColorRoles| -> Map<String, Value> {
        color_vars(theme)
            .into_iter()
            .map(|(suffix, hex)| (std::format!("md-sys-color-{suffix}"), Value::String(hex)))
            .collect()
    };

    let item = json!({
        "$schema": "https://ui.shadcn.com/schema/registry-item.json",
        "name": "theme-aphrody",
        "type": "registry:theme",
        "author": "aphrody-code",
        "title": "Aphrody Material 3",
        "description": "Material Design 3 theme generated by aphrody's m3-tokens (Rust). shadcn semantic tokens alias to the live --md-sys-color-* palette (cssVars.theme); the palette flips light/dark via cssVars.light and cssVars.dark. See docs/design/FUSION-PLAN.md.",
        "cssVars": {
            "theme": Value::Object(theme),
            "light": Value::Object(palette(&BASELINE)),
            "dark": Value::Object(palette(&BASELINE_DARK)),
        }
    });

    serde_json::to_string_pretty(&item)
        .map_err(|e| miette::miette!("serialize registry:theme: {e}"))
}
