// SPDX-License-Identifier: Apache-2.0
//! Docs preview pane — renders the workspace's `docs/SUMMARY.md` markdown
//! TOC inline inside aphrody-terminal.
//!
//! This is the integration point for the `aphrody-summary` crate
//! (matrix row `T-INT-summary`). Instead of shelling out to
//! `cargo run -p aphrody-summary`, the pane invokes the library entry point
//! [`aphrody_summary::generate`] in-process and emits an
//! [`LlmEvent::Markdown`] envelope on the [`crate::EventBus`].
//!
//! Two consumption modes are offered:
//!
//! - [`DocsPreviewPane::render`] — synchronous; returns the rendered markdown body directly (used
//!   by tests and CLI dumps).
//! - [`DocsPreviewPane::publish_to`] — pushes the same body onto an [`EventBus`] as
//!   `LlmEvent::Markdown { body }`, so any subscribed renderer (WASM, ratatui, etc.) picks it up
//!   via the existing broadcast channel.

use anyhow::Result;

use crate::{EventBus, LlmEvent};

/// Bridge between `aphrody-summary` and the terminal-llm event bus.
///
/// The struct is a zero-sized handle; all methods are associated functions
/// that call into `aphrody_summary` directly. Kept as a struct (rather than
/// free functions) for symmetry with the other registry types in this crate
/// (`SubAgentRegistry`, `McpStatusRegistry`, etc.) so future extensions
/// (configurable docs roots, caching, watch-based invalidation) have an
/// obvious place to land.
#[derive(Debug, Default, Clone, Copy)]
pub struct DocsPreviewPane;

impl DocsPreviewPane {
    /// Render the workspace's `docs/SUMMARY.md` TOC and return the markdown
    /// body as a `String`.
    ///
    /// Resolves the repo root via `CARGO_MANIFEST_DIR` (falling back to the
    /// current directory), walks the `docs/` tree, and assembles the same
    /// markdown that `cargo run -p aphrody-summary` writes to disk — but
    /// without writing.
    pub fn render() -> Result<String> {
        aphrody_summary::generate()
    }

    /// Render the docs preview and publish it as an
    /// [`LlmEvent::Markdown`] envelope on the supplied [`EventBus`].
    ///
    /// Returns the number of subscribers that received the event, or the
    /// underlying error if either generation or publication failed.
    pub fn publish_to(bus: &EventBus) -> Result<usize> {
        let body = Self::render()?;
        let count = bus
            .publish(LlmEvent::Markdown { body })
            .map_err(|e| anyhow::anyhow!("event bus has no subscribers: {e}"))?;
        Ok(count)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn docs_preview_pane_renders_summary() {
        let body = DocsPreviewPane::render().expect("docs preview render ok");
        assert!(!body.is_empty(), "rendered docs preview must not be empty");
        assert!(
            body.contains("# Summary"),
            "rendered body must contain the '# Summary' markdown heading; got: {body}"
        );
        assert!(
            body.contains("AUTO-GENERATED by aphrody-summary"),
            "rendered body must carry the auto-generated banner; got: {body}"
        );
    }

    #[tokio::test]
    async fn docs_preview_pane_publishes_markdown_event() {
        let bus = EventBus::new(8);
        let mut rx = bus.subscribe();

        let receivers =
            DocsPreviewPane::publish_to(&bus).expect("publish docs preview to event bus");
        assert!(receivers >= 1, "expected at least one subscriber, got {receivers}");

        let ev = rx.recv().await.expect("recv docs preview event");
        match ev {
            LlmEvent::Markdown { body } => {
                assert!(body.contains("# Summary"), "body must contain '# Summary'");
            },
            other => panic!("expected LlmEvent::Markdown, got {other:?}"),
        }
    }
}
