# SPDX-License-Identifier: Apache-2.0
#
# RPM spec for the `aphrody` cross-platform Rust CLI.
# Targets: Fedora 40+, RHEL 9 / CentOS Stream 9, Rocky 9, AlmaLinux 9.
#
# Build locally:
#     rpmbuild -ba packaging/rpm/aphrody.spec
#
# Hosted builds via Fedora COPR:
#     copr-cli build aphrody-code/aphrody packaging/rpm/aphrody.spec
#
# Upstream guideline reference:
#     https://docs.fedoraproject.org/en-US/packaging-guidelines/

Name:           aphrody
Version:        1.0.0~canary
Release:        1%{?dist}
Summary:        Cross-platform Rust CLI with embedded AGNTCY a2a/v0.4 manifest

License:        Apache-2.0
URL:            https://github.com/aphrody-code/aphrody
Source0:        https://github.com/aphrody-code/aphrody/archive/v%{version}.tar.gz#/%{name}-%{version}.tar.gz

# Build toolchain — Rust 2024 edition needs >= 1.85; 1.97 aligns with workspace.
BuildRequires:  rust >= 1.97
BuildRequires:  cargo
BuildRequires:  pkg-config
BuildRequires:  openssl-devel

# Runtime libs are picked up automatically by RPM's automatic dependency
# generator from the ELF binary (glibc, openssl). No explicit Requires needed.

ExclusiveArch:  x86_64 aarch64

%description
Aphrody is a cross-platform (Linux, Windows, WebAssembly) Rust CLI tool
that embeds an AGNTCY a2a/v0.4 collaboration manifest for agent-to-agent
coordination. It bundles diagnostic, scraping, DNS reconnaissance,
monorepo scanning, token inspection, and shell completions for
bash / zsh / fish / pwsh / elvish.

Linux Ubuntu 26.04 is the reference platform; Fedora / RHEL / Rocky /
AlmaLinux are first-class build targets through this spec.

# Strip debug-info package generation — release builds are -C strip=symbols.
%global debug_package %{nil}

%prep
%autosetup -n %{name}-%{version}

%build
# Pin CARGO_HOME inside the build tree so rpmbuild does not pollute $HOME
# and so the build remains hermetic when SOURCE_DATE_EPOCH is honoured.
export CARGO_HOME="$RPM_BUILD_DIR/cargo-home"
export RUSTFLAGS="${RUSTFLAGS} -C strip=symbols"
cargo build --release --locked --offline -p aphrody

%install
# Binary
install -Dm755 target/release/aphrody %{buildroot}%{_bindir}/aphrody

# Shell completions — generated by the binary itself.
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions
mkdir -p %{buildroot}%{_datadir}/zsh/site-functions
mkdir -p %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/aphrody completions bash \
    > %{buildroot}%{_datadir}/bash-completion/completions/aphrody
%{buildroot}%{_bindir}/aphrody completions zsh \
    > %{buildroot}%{_datadir}/zsh/site-functions/_aphrody
%{buildroot}%{_bindir}/aphrody completions fish \
    > %{buildroot}%{_datadir}/fish/vendor_completions.d/aphrody.fish

# LICENSE — installed under %{_licensedir} via the %license file marker below.
install -Dm644 LICENSE %{buildroot}%{_licensedir}/%{name}/LICENSE

%check
# Smoke-test the produced binary inside the buildroot.
%{buildroot}%{_bindir}/aphrody --version

%files
%license LICENSE
%{_bindir}/aphrody
%{_datadir}/bash-completion/completions/aphrody
%{_datadir}/zsh/site-functions/_aphrody
%{_datadir}/fish/vendor_completions.d/aphrody.fish

%changelog
* Sun May 17 2026 aphrody-code <noreply@aphrody-code.dev> - 1.0.0~canary-1
- Initial canary RPM package for Fedora / RHEL / Rocky / AlmaLinux.
- Ships /usr/bin/aphrody plus bash, zsh, fish completions.
- License installed via %%license macro; debuginfo subpackage disabled.
