#!/usr/bin/env bun
/**
 * scripts/gen_summary.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Auto-generate `docs/SUMMARY.md` (mdBook table of contents) from the docs/
 * directory tree.
 *
 * Usage:
 *   bun run scripts/gen_summary.ts
 *   bun run scripts/gen_summary.ts --check    # CI: fail if SUMMARY.md drifts
 *
 * Behaviour:
 *   - Top-level files (docs/*.md) are listed first in a curated order.
 *   - Subdirectories become groups, sorted alphabetically.
 *   - Within a group, README.md surfaces as the group anchor, then other .md
 *     files sorted alphabetically.
 *   - Files starting with `_`, `.`, or named `SUMMARY.md` are skipped.
 *   - Output: `docs/SUMMARY.md`.
 */

import { readdir, stat, readFile, writeFile } from "node:fs/promises";
import { join, relative, basename, sep } from "node:path";

const DOCS_ROOT = join(import.meta.dir, "..", "docs");
const SUMMARY_PATH = join(DOCS_ROOT, "SUMMARY.md");

// Curated top-level order — anything not here is appended alphabetically.
const TOP_LEVEL_ORDER = [
  "README.md",
  "PLAN.md",
  "DESIGN.md",
  "GOOGLE.md",
  "AWESOME.md",
  "libc.md",
  "bun-rs.md",
];

const SKIP_NAMES = new Set(["SUMMARY.md", ".DS_Store"]);
const SKIP_DIR_PREFIXES = ["_", "."];

type Entry =
  | { kind: "file"; name: string; relPath: string }
  | { kind: "dir"; name: string; entries: Entry[] };

async function scan(dir: string): Promise<Entry[]> {
  const names = await readdir(dir);
  const out: Entry[] = [];

  for (const name of names.sort()) {
    if (SKIP_NAMES.has(name)) continue;
    if (SKIP_DIR_PREFIXES.some((p) => name.startsWith(p))) continue;

    const full = join(dir, name);
    let st;
    try {
      st = await stat(full);
    } catch {
      // Skip broken symlinks / unreadable entries.
      continue;
    }

    if (st.isDirectory()) {
      const inner = await scan(full);
      if (inner.length === 0) continue;
      out.push({ kind: "dir", name, entries: inner });
    } else if (name.endsWith(".md")) {
      out.push({
        kind: "file",
        name,
        relPath: relative(DOCS_ROOT, full).split(sep).join("/"),
      });
    }
  }
  return out;
}

function titleize(name: string): string {
  // Strip extension, replace separators, prettify.
  const base = name.replace(/\.md$/, "");
  return base
    .split(/[-_]/)
    .map((w) => (w.length === 0 ? w : w[0]!.toUpperCase() + w.slice(1)))
    .join("-");
}

function renderTopLevel(entries: Entry[]): string {
  const files = entries.filter((e): e is Extract<Entry, { kind: "file" }> =>
    e.kind === "file",
  );
  const byName = new Map(files.map((f) => [f.name, f]));
  const ordered: string[] = [];

  // 1. Curated order first.
  for (const name of TOP_LEVEL_ORDER) {
    const f = byName.get(name);
    if (!f) continue;
    byName.delete(name);
    const title = name === "README.md" ? "Accueil" : titleize(name);
    ordered.push(`- [${title}](${f.relPath})`);
  }

  // 2. Remaining top-level files alphabetically.
  for (const [name, f] of [...byName.entries()].sort()) {
    const title = titleize(name);
    ordered.push(`- [${title}](${f.relPath})`);
  }

  return ordered.join("\n");
}

function renderGroup(dir: Extract<Entry, { kind: "dir" }>, depth: number): string {
  const indent = "  ".repeat(depth);
  const lines: string[] = [];

  // Group header. Use README.md as anchor if present, else dummy link.
  const readme = dir.entries.find(
    (e) => e.kind === "file" && e.name.toLowerCase() === "readme.md",
  ) as Extract<Entry, { kind: "file" }> | undefined;
  const groupName = titleize(dir.name);

  if (readme) {
    lines.push(`${indent}- [${groupName}](${readme.relPath})`);
  } else {
    lines.push(`${indent}- [${groupName}]()`);
  }

  // List children — files first, then sub-dirs.
  const files = dir.entries.filter(
    (e): e is Extract<Entry, { kind: "file" }> =>
      e.kind === "file" && e.name.toLowerCase() !== "readme.md",
  );
  const subdirs = dir.entries.filter(
    (e): e is Extract<Entry, { kind: "dir" }> => e.kind === "dir",
  );

  for (const f of files) {
    const title = titleize(f.name);
    lines.push(`${indent}  - [${title}](${f.relPath})`);
  }
  for (const sd of subdirs) {
    lines.push(renderGroup(sd, depth + 1));
  }

  return lines.join("\n");
}

async function build(): Promise<string> {
  const entries = await scan(DOCS_ROOT);
  const topLevel = renderTopLevel(entries);
  const groups = entries
    .filter((e): e is Extract<Entry, { kind: "dir" }> => e.kind === "dir")
    .map((d) => renderGroup(d, 0));

  const banner = [
    "<!--",
    "  AUTO-GENERATED by scripts/gen_summary.ts — DO NOT EDIT BY HAND.",
    "  Re-run with:  bun run scripts/gen_summary.ts",
    "-->",
    "",
    "# Summary",
    "",
  ].join("\n");

  return [banner, topLevel, "", ...groups, ""].join("\n");
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const checkMode = args.has("--check");

  const generated = await build();

  if (checkMode) {
    const existing = await readFile(SUMMARY_PATH, "utf8").catch(() => "");
    if (existing.trim() !== generated.trim()) {
      console.error(
        "✗ docs/SUMMARY.md is out of date. Run: bun run scripts/gen_summary.ts",
      );
      process.exit(1);
    }
    console.log("✓ docs/SUMMARY.md is up to date.");
    return;
  }

  await writeFile(SUMMARY_PATH, generated, "utf8");
  const lineCount = generated.split("\n").length;
  console.log(`✓ Generated docs/SUMMARY.md (${lineCount} lines)`);
}

main().catch((err: unknown) => {
  console.error("gen_summary failed:", err);
  process.exit(1);
});
