#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Setup environment variables for aphrody dev work (Linux / macOS / git-bash).
# Idempotent ; safe to re-run.
#
# Usage :
#   bash scripts/setup-dev-env.sh           # apply (writes to ~/.bashrc.d/aphrody.sh)
#   bash scripts/setup-dev-env.sh --check   # dry-run
#   bash scripts/setup-dev-env.sh --reset   # remove the snippet

set -euo pipefail

CHECK=0
RESET=0
for arg in "$@"; do
    case "$arg" in
        --check) CHECK=1 ;;
        --reset) RESET=1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Canonical env table (paired with scripts/setup-dev-env.ps1).
# ---------------------------------------------------------------------------
declare -A ENV_TABLE=(
    [CARGO_INCREMENTAL]="0"
    [SCCACHE_DIR]="$HOME/.cache/sccache"
    [SCCACHE_CACHE_SIZE]="10G"
    [CARGO_BUILD_JOBS]="7"
    [CARGO_NET_GIT_FETCH_WITH_CLI]="true"
    [CARGO_TERM_COLOR]="always"
    [RUST_BACKTRACE]="1"
    [BUN_RUNTIME_TRANSPILER_CACHE_PATH]="$HOME/.cache/bun-transpile"
    [APHRODY_A2A_ENDPOINT]="http://localhost:8788/jsonrpc"
    [APHRODY_LIVE_BACKEND]="gemini-oauth"
)

SNIPPET_PATH="$HOME/.bashrc.d/aphrody.sh"
mkdir -p "$(dirname "$SNIPPET_PATH")"

render_snippet() {
    echo "# SPDX-License-Identifier: Apache-2.0"
    echo "# Generated by aphrody/scripts/setup-dev-env.sh — do not edit by hand."
    echo "# Re-run setup-dev-env.sh to refresh."
    echo ""
    for k in "${!ENV_TABLE[@]}"; do
        echo "export $k='${ENV_TABLE[$k]}'"
    done | sort
    echo ""
    echo "# Ensure cache dirs exist."
    echo "mkdir -p \"\${SCCACHE_DIR}\" \"\${BUN_RUNTIME_TRANSPILER_CACHE_PATH}\""
}

if [[ $RESET -eq 1 ]]; then
    if [[ -f "$SNIPPET_PATH" ]]; then
        rm -f "$SNIPPET_PATH"
        echo "REMOVED  $SNIPPET_PATH"
    fi
    exit 0
fi

if [[ $CHECK -eq 1 ]]; then
    echo "Dry-run plan (no changes) :"
    render_snippet
    exit 0
fi

# Apply
render_snippet > "$SNIPPET_PATH"
echo "WROTE    $SNIPPET_PATH"
echo ""
echo "Add to your ~/.bashrc (idempotent) :"
echo "  [ -f \"\$HOME/.bashrc.d/aphrody.sh\" ] && source \"\$HOME/.bashrc.d/aphrody.sh\""
echo ""
echo "Or source it in this shell now :"
echo "  source $SNIPPET_PATH"
