// Auto-generated by @aphrody-code/ui Pentalingual Compiler

export const Theme = {
  colors: {
    "brand": {
        "primary": {
            "value": "#0078D7",
            "type": "color",
            "description": "WinClean core brand color"
        },
        "secondary": {
            "value": "#005A9E",
            "type": "color"
        }
    },
    "background": {
        "base": {
            "value": "#0F0F0F",
            "type": "color",
            "description": "Deep dark background"
        },
        "surface": {
            "value": "#1C1C1E",
            "type": "color",
            "description": "Elevated surface (cards, modals)"
        }
    },
    "text": {
        "primary": {
            "value": "#FFFFFF",
            "type": "color"
        },
        "secondary": {
            "value": "#A0A0A5",
            "type": "color"
        }
    },
    "status": {
        "success": {
            "value": "#28A745",
            "type": "color",
            "description": "Used for success states and Aphrody 'Joie'"
        },
        "warning": {
            "value": "#FFC107",
            "type": "color",
            "description": "Used for warnings and Aphrody 'Choque'"
        },
        "danger": {
            "value": "#DC3545",
            "type": "color",
            "description": "Used for errors and Aphrody 'Colere'"
        }
    }
},
  spacing: {
    "1": {
        "value": "0.25rem",
        "description": "4px"
    },
    "2": {
        "value": "0.5rem",
        "description": "8px"
    },
    "3": {
        "value": "0.75rem",
        "description": "12px"
    },
    "4": {
        "value": "1rem",
        "description": "16px"
    },
    "6": {
        "value": "1.5rem",
        "description": "24px"
    },
    "8": {
        "value": "2rem",
        "description": "32px"
    },
    "12": {
        "value": "3rem",
        "description": "48px"
    },
    "16": {
        "value": "4rem",
        "description": "64px"
    }
},
  typography: {
    "fontFamily": {
        "sans": {
            "value": "'Inter', 'Segoe UI Variable', 'Segoe UI', sans-serif"
        },
        "mono": {
            "value": "'Cascadia Code', 'Consolas', monospace"
        }
    },
    "fontSize": {
        "xs": {
            "value": "0.75rem"
        },
        "sm": {
            "value": "0.875rem"
        },
        "base": {
            "value": "1rem"
        },
        "lg": {
            "value": "1.125rem"
        },
        "xl": {
            "value": "1.25rem"
        },
        "2xl": {
            "value": "1.5rem"
        },
        "3xl": {
            "value": "1.875rem"
        }
    },
    "fontWeight": {
        "regular": {
            "value": "400"
        },
        "medium": {
            "value": "500"
        },
        "bold": {
            "value": "700"
        }
    }
}
};
