// SPDX-License-Identifier: Apache-2.0
import type { Blade, Ratchet, Bit } from "./types";

export const BLADES: Blade[] = [
  {
    id: "dran_sword",
    name: "Dran Sword",
    type: "Attack",
    weight: 35.0,
    spinDirection: "Right",
    description: "Classic high-impact 3-sided metallic blade designed for aggressive smash attacks.",
    attack: 9,
    defense: 2,
    stamina: 3,
  },
  {
    id: "hell_scythe",
    name: "Hell Scythe",
    type: "Balance",
    weight: 32.5,
    spinDirection: "Right",
    description: "Four thick blades provide a perfect balance of recoil and defensive stamina.",
    attack: 6,
    defense: 5,
    stamina: 5,
  },
  {
    id: "wizard_arrow",
    name: "Wizard Arrow",
    type: "Stamina",
    weight: 31.5,
    spinDirection: "Right",
    description: "Smooth, circular shape that minimizes air resistance to maximize spin longevity.",
    attack: 3,
    defense: 4,
    stamina: 9,
  },
  {
    id: "knight_shield",
    name: "Knight Shield",
    type: "Defense",
    weight: 33.0,
    spinDirection: "Right",
    description: "Multi-layered perimeter designed to absorb and distribute shock from incoming attacks.",
    attack: 4,
    defense: 8,
    stamina: 4,
  },
  {
    id: "cobalt_drake",
    name: "Cobalt Drake",
    type: "Attack",
    weight: 38.0,
    spinDirection: "Right",
    description: "Extremely heavy, limited-edition blade built for absolute crushing power.",
    attack: 10,
    defense: 4,
    stamina: 2,
  },
  {
    id: "phoenix_wing",
    name: "Phoenix Wing",
    type: "Attack",
    weight: 38.5,
    spinDirection: "Right",
    description: "Heavily painted metal ring that concentrates weight on the outer rim for ultimate momentum.",
    attack: 10,
    defense: 3,
    stamina: 3,
  },
  {
    id: "unicorn_sting",
    name: "Unicorn Sting",
    type: "Balance",
    weight: 32.2,
    spinDirection: "Right",
    description: "Features a split design with one side for attack and the other for defense.",
    attack: 6,
    defense: 6,
    stamina: 5,
  },
  {
    id: "shark_edge",
    name: "Shark Edge",
    type: "Attack",
    weight: 35.2,
    spinDirection: "Right",
    description: "Serrated, upward-slanted teeth designed to lift and burst opponents from below.",
    attack: 9,
    defense: 1,
    stamina: 2,
  },
  {
    id: "cobalt_dragoon",
    name: "Cobalt Dragoon",
    type: "Attack",
    weight: 38.2,
    spinDirection: "Left",
    description: "The first Left-spin blade of the X generation. Features heavy, reversed dragon wings.",
    attack: 10,
    defense: 3,
    stamina: 2,
  },
  {
    id: "black_shell",
    name: "Black Shell",
    type: "Defense",
    weight: 34.5,
    spinDirection: "Right",
    description: "Inverted shell design that deflects impacts downward to preserve spin velocity.",
    attack: 3,
    defense: 9,
    stamina: 3,
  },
];

export const RATCHETS: Ratchet[] = [
  {
    id: "3_60",
    name: "3-60",
    weight: 6.2,
    points: 3,
    height: 60,
    description: "Low-height 3-sided ratchet. Highly popular for attack combos.",
    burstResistance: 6,
  },
  {
    id: "4_60",
    name: "4-60",
    weight: 6.4,
    points: 4,
    height: 60,
    description: "Low-height 4-sided ratchet. Balanced distribution.",
    burstResistance: 6,
  },
  {
    id: "5_60",
    name: "5-60",
    weight: 6.6,
    points: 5,
    height: 60,
    description: "Low-height 5-sided ratchet. Circular, heavy, and very hard to burst.",
    burstResistance: 7,
  },
  {
    id: "9_60",
    name: "9-60",
    weight: 6.8,
    points: 9,
    height: 60,
    description: "Extremely circular low-height ratchet with excellent weight distribution.",
    burstResistance: 8,
  },
  {
    id: "3_80",
    name: "3-80",
    weight: 6.5,
    points: 3,
    height: 80,
    description: "High-height 3-sided ratchet. Allows striking from higher angles.",
    burstResistance: 5,
  },
  {
    id: "5_80",
    name: "5-80",
    weight: 6.9,
    points: 5,
    height: 80,
    description: "High-height 5-sided ratchet. Extra weight and defensive capability.",
    burstResistance: 6,
  },
];

export const BITS: Bit[] = [
  {
    id: "flat",
    name: "Flat",
    type: "Attack",
    weight: 2.1,
    speed: 9,
    stamina: 2,
    defense: 3,
    burstResistance: 8,
    description: "Flat plastic tip that rides the X-line stadium rail aggressively.",
  },
  {
    id: "gear_flat",
    name: "Gear Flat",
    type: "Attack",
    weight: 2.3,
    speed: 10,
    stamina: 1,
    defense: 2,
    burstResistance: 9,
    description: "Gears extend to the tip's bottom for maximum X-dash speed and recoil.",
  },
  {
    id: "taper",
    name: "Taper",
    type: "Balance",
    weight: 2.2,
    speed: 7,
    stamina: 5,
    defense: 5,
    burstResistance: 8,
    description: "Slanted cone shape that transitions from speed to center stamina over time.",
  },
  {
    id: "ball",
    name: "Ball",
    type: "Stamina",
    weight: 2.0,
    speed: 3,
    stamina: 9,
    defense: 4,
    burstResistance: 4,
    description: "Spherical tip that provides superb tilt recovery and low friction.",
  },
  {
    id: "needle",
    name: "Needle",
    type: "Defense",
    weight: 2.0,
    speed: 2,
    stamina: 6,
    defense: 9,
    burstResistance: 4,
    description: "Pointy cone tip that holds the exact center of the stadium.",
  },
  {
    id: "point",
    name: "Point",
    type: "Balance",
    weight: 2.2,
    speed: 6,
    stamina: 7,
    defense: 6,
    burstResistance: 6,
    description: "Ball tip with a tiny flat center. Delivers dynamic shifts between attack and stamina.",
  },
  {
    id: "hexa",
    name: "Hexa",
    type: "Defense",
    weight: 2.4,
    speed: 4,
    stamina: 5,
    defense: 9,
    burstResistance: 7,
    description: "Hexagonal flat tip that excels at stabilizing after taking heavy recoil.",
  },
];
export const PARTS_CATALOG = {
  blades: BLADES,
  ratchets: RATCHETS,
  bits: BITS,
};

export function findBlade(id: string): Blade | undefined {
  return BLADES.find((b) => b.id === id);
}

export function findRatchet(id: string): Ratchet | undefined {
  return RATCHETS.find((r) => r.id === id);
}

export function findBit(id: string): Bit | undefined {
  return BITS.find((b) => b.id === id);
}
